cefsharp/CefSharp

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/ClientAdapter.h, CefSharp/IJsDialogHandler.cs, CefSharp3.sln.DotSettings
Extended IJsDialogHandler to catch on OnBeforeUnload Javascript Dialog messages.
This should fix the issue with #712
=> Extend IJsDialogHandler To Include OnBeforeUnload Dialogs

CefSharp.OffScreen/ChromiumWebBrowser.cs
This fix ensures the Address field returns the correct value after construction (instead of null).  The Address field setter is now private as callers should use Load() to change url.
```C#
var browser = new CefSharp.OffScreen.ChromiumWebBrowser("https://www.google.com/");
var a = browser.Address; // now returns "https://www.google.com/" instead of null
browser.Address = "about:blank"; // now generates compiler error instead of doing nothing
```
=> Fix OffScreen's Address field

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/ClientAdapter.h, CefSharp.Example/CefExample.cs, CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.WinForms.Example/BrowserTabUserControl.cs, CefSharp.WinForms.Example/CefSharp.WinForms.Example.csproj, CefSharp.WinForms.Example/GeolocationHandler.cs, CefSharp.WinForms/ChromiumWebBrowser.cs, CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj, CefSharp.Wpf.Example/Handlers/GeolocationHandler.cs, CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/CefSharp.csproj, CefSharp/IGeolocationHandler.cs, CefSharp/IWebBrowser.cs
delegating the request to a CefSharp.IGeolocationHandler implementation.  This allows CefSharp to permit geolocation requests.
This implements https://github.com/cefsharp/CefSharp/issues/332 .
=> Implement CefGeolocationHandler::OnRequestGeolocationPermission

CefSharp.WinForms/WebView.cpp, CefSharp.WinForms/WebView.h, CefSharp.Wpf/WebView.cpp, CefSharp.Wpf/WebView.h, CefSharp/CefSharp.vcxproj, CefSharp/CefSharp.vcxproj.filters, CefSharp/ClientAdapter.cpp, CefSharp/IWebBrowser.h, CefSharp/LoadCompletedEventArgs.h, CefSharp/LoadStartedEventArgs.h
Hi guys,
Just a (very) quick one, since we seem to need this at work. Doing some clever JS hacks that breaks if we do a `document.location`-based redirect, so that's why I'm experimenting in this direction - *maybe injecting some JS early in the page load can work*? You know the feeling. :smile: 
@amaitland or @jornh, I assume I have your blessing to merge this into the CefSharp1 branch? :wink: (We're still using CefSharp1, will hopefully upgrade later this year as it looks now.)
=> Added LoadStarted event handler

CefSharp.WinForms/ChromiumWebBrowser.cs
CEF.Shutdown in some cases would call SetFocus when managedCefBrowserAdapter was null.
=> Check for null object to prevent NullException in SetFocus

CefSharp.Wpf/ChromiumWebBrowser.cs
1. Unsubscription from CleanupElement.Unloaded event
2. Unsubscription from tooltipTimer.Tick event
3. Removing source hook
=> Fixed memory leak issues:

CefSharp.Core/Cef.h
Custom schemes are much easier to deal with if you can use XHR with them, so on the theory that these APIs work, expose them from CefSharp.
See CEF issues 246 and 950 for more details.
Let me know if these methods should go somewhere else.
Fyi,
Bill
=> Expose Cross-Origin Whitelist from Cef.XXX as static methods.

CefSharp.Core/Internals/RenderClientAdapter.h, CefSharp.Core/ManagedCefBrowserAdapter.h, CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/Internals/IRenderWebBrowser.cs
https://github.com/cefsharp/CefSharp/issues/836
=> Use device scale factor to support higher DPI on WPF

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/StreamAdapter.cpp, CefSharp.Core/Internals/StreamAdapter.h, CefSharp.Example/CefExample.cs, CefSharp/ResourceHandler.cs
...emoryStreams, and add lame header to ResourceHandler usage in CefExample.cs.
Additionally, allocate Headers NameValueCollection in constructor of ResourceHandler.
Sadly, without a change to ClientAdapter.cpp to pass the header data to CEF due to a debug flavor bug in CEF, you can't easily test this change. :(
If you do test this with the CEF change or a Release flavor with the ClientAdapter.cpp change, then this works correctly.
Bill
=> Enhance StreamAdapter to more effeciently deal with MemoryStream

CefSharp/CefErrorCode.cs
From Chromium's `net/base/net_error_list.h`.
Also added a comment to indicate where the error codes were sourced from.
Also changed copyright date to end in `2015` (should this be done for all files at once, or individually as they are updated? not sure).
Addresses issue #870 
I used the trunk version of `net_error_list.h` for the error codes.  The only interesting thing was that Chromium has added several new certificate errors, so `CertEnd` is now `-213` instead of `-208`, however this should be harmless as `-208` should not be reported by older versions of Chromium anyway.
=> Added many missing error codes to CefErrorCode.cs

CefSharp.Wpf/ChromiumWebBrowser.cs
This one adds a `TitleChanged` event handler, which is needed in my use case (so that I don't have to do dirty hacks).
Sorry for the whitespace changes; they were included without without extra charge. :wink: 
OK to merge?
=> Added a TitleChanged event handler

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Example/RequestHandler.cs, CefSharp/IRequestHandler.cs
Closing #829. Adding ```IsMainFrame``` to the ```OnBeforeBrowse``` method.
=> Passing IsMainFrame as parameter to the OnBeforeBrowse

CefSharp.Core/Internals/CefRequestWrapper.cpp, CefSharp.Core/Internals/CefRequestWrapper.h
This fixes a bug where unicode characters were not being decoded correctly in the POST request body in CefRequest.
This meant that Unicode text was being corrupted in custom schemes and `RequestHandler`.
For example, U with umlaut - `"Ü"` - that was sent correctly as utf-8 in an AJAX request, was then incorrectly decoded using the default ASCII codepage as `"Ã"`).
=> Use correct string encoding in CefRequest.Body

CefSharp.WinForms/ChromiumWebBrowser.cs, CefSharp.WinForms/Internals/DefaultFocusHandler.cs
instead of internal so that you can subclass and reuse the tricky default OnGotFocus implementation.
Add doc comment warnings about the danagers of overriding IFocusHandler.OnGotFocus for WinForm ChromiumWebBrowsers.
Thoughts?
Bill
=> Make DefaultFocusHandler public class

CefSharp.Core/Cef.h, CefSharp.Core/CefSettings.h, CefSharp.Example/CefExample.cs, CefSharp/CefSharp.csproj, CefSharp/DependencyChecker.cs
This is a rough first draft of `DependencyChecker`. Basically loops through list of all Cef/CefSharp dependencies.
Creating this PR before I go too far, some questions to be answered I think.
- Should we provide the option to validate have some dependencies marked as optional?
- What's the expected output if calling from user land? Is a list of strings containing which files are missing ok? Would people just prefer a formatted string?
- Anyone have any thoughts on obtaining the path? I've started with the `ExecutingAssembly` and allowed an overload so that users can call themselves.
Will include an overload for `Cef.Initialize()` that enables/disables the dependency check when I'm happy the other questions have been answered.
Resolves #876
=> Implement DependencyChecker

CefSharp.Wpf/ChromiumWebBrowser.cs
This avoids win 8/8.1 menu alignment settings where they can cause devices to not show relative positioned popups where expected.  
This fixes issue #906
=> WPF Popup - Change to absolute positioning

CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.WinForms/ChromiumWebBrowser.cs, CefSharp.Wpf/ChromiumWebBrowser.cs
http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefLoadHandler.html#OnLoadStart%28CefRefPtr%3CCefBrowser%3E,CefRefPtr%3CCefFrame%3E%29
`For notification of overall browser load status use OnLoadingStateChange instead.`
Initially just migrating `WPF` control. When it's configured, update the other two flavours.
=> Resolve: IsLoaded is unreliable

CefSharp.Core/Cef.h, CefSharp.Core/Internals/CefSharpApp.h, CefSharp.Example/CefExample.cs
Added a basic delegate to expose OnContextInitialized
If anyone has a better/cleaner/neater way, I'm open to suggestions. `Action` seemed simple and follows the other patterns used.
=> Add OnContextInitialized Delegate

CefSharp.Core/ManagedCefBrowserAdapter.h, CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.WinForms/ChromiumWebBrowser.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/IWebBrowser.cs, CefSharp/Internals/JavascriptObjectRepository.cs
Used to give the dev the possibility to decide wether JS methods/objects/parameters should be automatically made first letter lowercase or not.
=> Added parameter for lowercasing JS functions (or not)

CefSharp.Core/CefSharp.Core.vcxproj, CefSharp.Core/ManagedCefBrowserAdapter.h, CefSharp.WinForms.Example/BrowserForm.Designer.cs, CefSharp.WinForms.Example/BrowserForm.cs
GetZoomLevel is required to be called from the UI thread, but it has a failure mode of just returning 0 when its not on the UI thread. Here's a cheesy temporary solution to avoid adding a full on GetZoomLevelAsync method that returns a .Net task.
Bill
=> Call GetZoomLevel On CEF UI Thread

CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.WinForms/ChromiumWebBrowser.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/IWebBrowser.cs, CefSharp/Internals/JavascriptObjectRepository.cs
As per discussion starting https://github.com/cefsharp/CefSharp/pull/923#issuecomment-92310713
=> Rename lowerCaseJavascriptNames to camelCaseJavascriptNames

CefSharp.Core/ManagedCefBrowserAdapter.h
Use GetFocusedFrame() for all clipboard and undo/redo stack activities.
Hopefully, this will fix #928 
If we merge this in, I can merge this into 2272 as well.
=> Clipboard ops don't work from WinForms menubar

CefSharp.OffScreen.Example/Program.cs, CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.OffScreen/GdiBitmapInfo.cs
Attempt to improve efficiency of OffScreen rendering by only creating a new bitmap when the old one changes in size (same behavior as WPF).
Moved bitmap creation into GdiBitmapInfo
=> OffScreen Performance Tweak

CefSharp.Core/Internals/CefTaskScheduler.h, CefSharp.Core/Internals/CefTaskWrapper.h
Log an ERROR message via CEF logging, and throw an appropriate exception on thread pool thread.
The idea is that the AppDomain's UnhandledException or Application.ThreadException handler will get called.
This PR is for discussion, I'll be testing out the approach with a non-CEF sample app in a bit.
=> Propagate TaskWrapper exceptions somewhere

.gitignore, CefSharp.props
Redirect VS2015 to use VS2013 binaries and toolset in CefSharp.props.
Added .vs folder to .gitignore, as it contains the .suo files and
intellisense database used by VS2015. See
http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/6079923-store-project-related-information-in-vs-folder-to
for more details.
=> Add Visual Studio 2015 support

CefSharp.Core/Internals/CefTaskScheduler.h, CefSharp.Core/Internals/CefTaskWrapper.h
`CefTaskWrapper` now implements `CefTask` and can be passed directly into `CefPostTask` - replace 
`NewCefRunnableMethod`
=> Implement CefTask

CefSharp.Wpf/Rendering/InteropBitmapInfo.cs
The OnPaint call arrives on a thread other than the UI thread. This means it is possible that the InvokeRenderAsync method, which is dispatched back to the UI thread, will get called after the Dispose method. In this case, a NullReferenceException is thrown, because FileMappingHandle is no longer set.
=> WPF - Handle case where Bitmap in WpfBitmapInfo is null

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/ClientAdapter.h, CefSharp.Example/RequestHandler.cs, CefSharp/IRequestHandler.cs
There is no `IDisplayHandler` interface so added the method to `IRequestHandler` as that seemed the next best place.
=> Add OnFaviconURLChange

CefSharp.Core/CefSharp.Core.vcxproj, CefSharp.Core/CefSharp.Core.vcxproj.filters, CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/JsDialogCallback.h, CefSharp.Example/JsDialogHandler.cs, CefSharp/CefJsDialogType.cs, CefSharp/CefSharp.csproj, CefSharp/IJsDialogCallback.cs, CefSharp/IJsDialogHandler.cs
Whilst I understand that the ideal of having the types split into different methods was nice from a user point of view, I think we kept functionality from users that was exposed.
So the callback wrapper has been added so can now be executed async. SuppressMessage is now possible.
Fixes #999
Breaking changes 
- `IJsDialogHandler.OnJSAlert` Removed
- `IJsDialogHandler.OnJSConfirm` Removed
- `IJsDialogHandler.OnJSPrompt` Removed
- `IJsDialogHandler.OnJSDialog ` Added
=> Rewrite OnJSDialog so now matches the Cef API

CefSharp.Core/Internals/CookieVisitor.cpp, CefSharp/CefSharp.csproj, CefSharp/Cookie.cs, CefSharp/ICookieVisitor.cs
`CefCookie` doesn't quite map to `System.Net.Cookie`, so create a special class to represent.
Resolve #338
Breaking change (Though shouldn't be a problem as the type is still called cookie, would only be if explicitly identified using namespace).
=> Create a Cookie class to represent the CefCookie

CefSharp.Example/CefExample.cs, CefSharp/DependencyChecker.cs
As requested in https://github.com/cefsharp/CefSharp/issues/1007, here is a pull request containing only the change to automatically detect Windows XP:
Previously, it was the main program's responsibility to set `IsWindowsXp` if necessary, but that was problematic because it wasn't possible to set it before its value was used. But it's easy enough to detect automatically anyway, so it's probably nicer to just do that.
=> Automatically detect Windows XP.

CefSharp.Core/BrowserSettings.h, CefSharp.Core/ManagedCefBrowserAdapter.h, CefSharp.Wpf/ChromiumWebBrowser.cs
Currently, ManagedCefBrowserAdapter always sets transparent to TRUE when setting windowless mode.
Transparency isn't always desired, and attempting to place the browser control in a painted outer control can have ugly side-effects when resizing the app, if its colour is different from the containing window.
This PR lets the ChromiumWebBrowser specify whether transparency should be set.
=> Allow app to disable transparent background in windowless mode

CefSharp.Core/Internals/DownloadAdapter.cpp
Fix for issue #1031
Automatically close blank popups that appear when downloads are started in a separate window, once the download is done (complete, failed or cancelled).
Test the fix here:
https://jsfiddle.net/yLk7d3z8/
=> Auto-close blank popups when download is complete

CefSharp.Wpf/ChromiumWebBrowser.cs
Related to #583
Mark ChromiumWebBrowser.SourceHook as protected virtual so inherited controls can override the default SourceHook handling of messages.
=> Make SourceHook virtual for Wpf ChromiumWebBrowser

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/ClientAdapter.h, CefSharp.Core/ManagedCefBrowserAdapter.cpp, CefSharp.Core/ManagedCefBrowserAdapter.h, CefSharp.Example/RequestHandler.cs, CefSharp.WinForms.Example/KeyboardHandler.cs, CefSharp/IKeyboardHandler.cs, CefSharp/ILifeSpanHandler.cs, CefSharp/IPopupHandler.cs, CefSharp/IRequestHandler.cs, CefSharp/Internals/IBrowserAdapter.cs
Trying to reduce the code complexity a little bit. 
More changes to come.
=> Continued API Rewrite

CefSharp.WinForms.Example/CefSharp.WinForms.Example.csproj, CefSharp.WinForms.Example/Program.cs, CefSharp.Wpf.Example/App.xaml.cs
Add Message Box into WinForms and WPF examples to alert users they need to compile in Release mode when running outside of Visual Studio
=> Display Release Mode Message Box In Examples

CefSharp.Core/BrowserSettings.h, CefSharp.Core/ManagedCefBrowserAdapter.cpp, CefSharp/CefSharp.csproj, CefSharp/CefState.cs
Decompiled code showed `ValueType` before and how shows the correct type
Need to double check over the `cef_state_t` conversions. I've simplified them, though they can likely be simplified again.
=> BrowserSettings map to Enabled/Disabled/Default Enum

CefSharp.Wpf/ChromiumWebBrowser.cs
Fix NullReferenceException in WPF ChromiumWebBrowser when Address is set before OnApplyTemplate is called
See #1110
=> NullReferenceException when Address is set before OnApplyTemplate

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.h, CefSharp.BrowserSubprocess.Core/CefAppWrapper.cpp, CefSharp.BrowserSubprocess.Core/CefAppWrapper.h, CefSharp.BrowserSubprocess.Core/CefBrowserWrapper.cpp, CefSharp.BrowserSubprocess.Core/CefBrowserWrapper.h, CefSharp.BrowserSubprocess.Core/JavascriptCallbackRegistry.cpp, CefSharp.BrowserSubprocess.Core/JavascriptCallbackRegistry.h, CefSharp.BrowserSubprocess.Core/JavascriptCallbackWrapper.cpp, CefSharp.BrowserSubprocess.Core/JavascriptCallbackWrapper.h, CefSharp.BrowserSubprocess.Core/JavascriptMethodHandler.cpp, CefSharp.BrowserSubprocess.Core/JavascriptMethodHandler.h, CefSharp.BrowserSubprocess.Core/JavascriptRootObjectWrapper.cpp, CefSharp.BrowserSubprocess.Core/JavascriptRootObjectWrapper.h, CefSharp.Core/Internals/CefFrameWrapper.cpp, CefSharp.Core/Internals/CefSharpBrowserWrapper.cpp, CefSharp.Core/Internals/CefSharpBrowserWrapper.h, CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/ClientAdapter.h, CefSharp.Core/Internals/JavascriptCallbackFactory.cpp, CefSharp.Core/Internals/JavascriptCallbackFactory.h, CefSharp.Core/Internals/JavascriptCallbackProxy.cpp, CefSharp.Core/Internals/JavascriptCallbackProxy.h, CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj, CefSharp.Wpf.Example/Controls/CefSharpCommands.cs, CefSharp.Wpf.Example/MainWindow.xaml, CefSharp.Wpf.Example/MainWindow.xaml.cs
- Added a menu to the WPF example so it's easy to access the Binding Test page (should probably add some more test pages in as well)
- Minor code consistency refactorings, going forward constructor/finalizer/descructor blocks will be in the header files (may even considering remove cpp files for classes of small enough size)
- Check if browser is disposed before sending ipc message
- Always create a response message so errors can be returned from `render process ipc`.
=> Followup changes for js callback ipc

CefSharp.WinForms/Internals/ControlExtensions.cs
Fixes NullReferenceException exception when browser control is removed from a form but not disposed as should be added back to the form at some point of time:
```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
at CefSharp.WinForms.Internals.ControlExtensions.IsActiveControl(System.Windows.Forms.Control)
at CefSharp.WinForms.Internals.ParentFormMessageInterceptor.WndProc(System.Windows.Forms.Message ByRef)
at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)
at System.Windows.Forms.UnsafeNativeMethods.PeekMessage(MSG ByRef, System.Runtime.InteropServices.HandleRef, Int32, Int32, Int32)
at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMs …
```
=> Fixed NullReferenceException on ControlExtensions.IsActiveControl call

CefSharp.Core/ManagedCefBrowserAdapter.h
This fixes a NullReferenceException when disposing a ChromiumWebBrowser prior to initialization.
To reproduce the bug, modify `CefSharp.WinForms.Example\BrowserTabUserControl.cs` to the following:
```
line 21
browserPanel.Controls.Add(browser);
+           browserPanel.Visible = false;
```
Then start the `CefSharp.WinForms.Example` application and close the main window.  Because the `_browserWrapper` was never initialized, a `NullReferenceException` would occur on the line `_browserWrapper->CloseBrowser(true);`.
=> ManagedCefBrowserAdapter can now be disposed before initialization

CefSharp.WinForms/ChromiumWebBrowser.cs
Fixes following crash:
```
Exception: System.Exception
Message: 'Browser Is Not yet initialized. Use the IsBrowserInitializedChanged event and checkthe IsBrowserInitialized property to determine when the browser has been intialized.'
Source: CefSharp
Stacktrace:
at CefSharp.WebBrowserExtensions.ThrowExceptionIfBrowserNotInitialized(IWebBrowser browser)
at CefSharp.WinForms.ChromiumWebBrowser.SetFocus(Boolean isFocused)
at CefSharp.WinForms.ChromiumWebBrowser.OnGotFocus(EventArgs e)
at System.Windows.Forms.Control.WmSetFocus(Message& m)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
=> OnGotFocus no longer calls SetFocus if browser not initialized.

CefSharp.WinForms.Example/BrowserTabUserControl.cs, CefSharp.WinForms.Example/CefSharp.WinForms.Example.csproj, CefSharp.WinForms.Example/ChromeWidgetMessageInterceptor.cs
=> Add ChromeWidgetMessageInterceptor to WinForms Example

CefSharp.Core/Internals/CefCallbackWrapper.h
Users have no way to determine whether a callback has been disposed, resulting in the following crash if the callback is fired after disposal.  This change silently ignores the method calls.  Another approach would have been to add an `IsDisposed` flag that users must check but that seems more error-prone.
Because callbacks are typically executed asynchronously there is a good chance that they fire after the callback and/or the browser control has been disposed.  This happens occasionally in my app, and adding a `if (!browser.IsDisposed)` check prior to the callback being fired was not adequate to protect against the `NullReferenceException`.
I'm re-running my tests now to make sure this fixes it.
```
Exception: System.NullReferenceException
Message: 'Object reference not set to an …
```
=> Ignore callback usage after dispose

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/ManagedCefBrowserAdapter.cpp, CefSharp.Core/ManagedCefBrowserAdapter.h, CefSharp.Example/CefExample.cs, CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.WinForms/ChromiumWebBrowser.cs, CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj, CefSharp.Wpf.Example/Controls/CefSharpCommands.cs, CefSharp.Wpf.Example/Handlers/LifespanHandler.cs, CefSharp.Wpf.Example/MainWindow.xaml, CefSharp.Wpf.Example/MainWindow.xaml.cs, CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/ILifeSpanHandler.cs, CefSharp/Internals/IWebBrowserInternal.cs
Retarget #1015 against `master`.
- Basic support for `WinForms` should now be implemented
- Simplified, now methods are accessible through `IPopupHandler` rather than having conditional checks littered through the code.
=> Support for Custom Popup

CefSharp.Wpf/ChromiumWebBrowser.cs
I believe the new offscreen popup feature had a little problem, namely that the offscreen browser is created for the wpf control even if it had a parent. This is just a minimal fix for that, maybe it shouldn't even be a PR :smile:.
=> Offscreen browser is not created for wpf control when it has parent

CefSharp.Core/Internals/RenderClientAdapter.h, CefSharp.Core/ManagedCefBrowserAdapter.cpp, CefSharp.Core/ManagedCefBrowserAdapter.h, CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/Internals/IRenderWebBrowser.cs
Resolves https://github.com/cefsharp/CefSharp/issues/1154
Exposed the necessary functions for start drag to work:
* StartDragging (RenderClientAdapter)
* OnDragSourceEndedAt (ManagedCefBrowserAdapter)
* OnDragSourceSystemDragEnded (ManagedCefBrowserAdapter)
Implemented IRenderWebBrowser.StartDragging for the WPF
ChromiumWebBrowser.
TODO: Would like to add an adorner layer for the dragged text (using the
supplied fragment html), but feels like a project for later.
=> Implement start drag for WPF browser

CefSharp.Core/CefSharp.Core.vcxproj
This makes it easier to figure out `.dmp` crash dumps where CefSharp.Core.dll is part of the stack, like in the following:
```
libcef.dll!`anonymous namespace'::PureCall()  Line 29	C++
libcef.dll!_purecall()  Line 58	C
libcef.dll!CefCppToC<CefCallbackCppToC,CefCallback,_cef_callback_t>::Release()  Line 110	C++
libcef.dll!CefCppToC<CefRequestCallbackCppToC,CefRequestCallback,_cef_request_callback_t>::struct_release(_cef_base_t * base)  Line 148 + 0xa bytes	C++
CefSharp.Core.dll!000007feed2ede70() 	
[Frames below may be incorrect and/or missing, no symbols loaded for CefSharp.Core.dll]	
[Managed to Native Transition]	
CefSharp.Core.dll!CefSharp.Internals.MCefRefPtr<CefCallback>.op_Assign() + 0xfe bytes	
CefSharp.Core.dll!CefSharp.CefCallbackWrapper.Dispose(bool A_0) + 0x28 bytes …
```
=> Generate CefSharp.Core.pdb file for Release builds

CefSharp.Core/Internals/CefCallbackWrapper.h
Because `ResourceHandlerWrapper` already takes care of this.  Fixes `AccessViolationException` noted in #1143
=> Do not self-dispose CefCallbackWrapper

CefSharp/Internals/JavascriptObjectRepository.cs
Small change that fixes the exception handling in js binding method calls. All errors had the same target invocation error message and not the underlying one.
=> TargetInvocationException is converted properly in JavascriptObjectRepository.TryCallMethod

CefSharp.BrowserSubprocess.Core/JavascriptMethodHandler.cpp, CefSharp/Internals/JavascriptObjectRepository.cs
Added detailed exception string generation for exceptions in injected native functions / properties.
In contrast to #1253 this version does not use custom formatting for the exceptions
Output of this version using the ExceptionTest of #1254
```
Exception string for nested exceptions:
System.InvalidOperationException: Could not execute method: triggerNestedExceptions() - Missing Parameters: 0 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.OperationCanceledException: Nested Exception Canceled ---> System.InvalidOperationException: Nested Exception Invalid ---> System.DivideByZeroException: Attempted to divide by zero. 
at CefSharp.Example.ExceptionTestBoundObject.DivisionByZero(Int32 zero) in …
```
=> Feature default exception strings browser subprocess

CefSharp.Core/Internals/CefCallbackWrapper.h, CefSharp.Core/ResourceHandlerWrapper.cpp, CefSharp.Core/ResourceHandlerWrapper.h, CefSharp.Example/CefSharpSchemeHandler.cs, CefSharp.Example/DownloadHandler.cs, CefSharp.Example/RequestHandler.cs, CefSharp.WinForms.Example/Handlers/GeolocationHandler.cs, CefSharp.Wpf.Example/Handlers/GeolocationHandler.cs
This reverts  #1246, instead modify `ResourceHandlerWrapper` so it no longer disposes of the callback.
Also added/update how the examples deal with callbacks.
=> Improve Callback Handling in Examples

build.ps1
Updated the default redist version in the build script from 3.2454.1317 to 3.2454.1326
cefsharp/CefSharp#1306
=> Upgrade build.ps1 to reference cef.redist 3.2454.1326

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp
Branch master, currently 7aa128781df73d37d9be9e1534338d61943d04a9
I discovered this issue when investigating the erroneous execution of 
```
await browser.EvaluateScriptAsync("document.getElementById('lst-ib').value = 'CefSharp Was Here!'");
```
in the CefSharp.OffScreen.Example
Since e9675a2c3e104405b15f4f9cad54778b0cc232a8
In this commit the execution of evaluated script will stop if no root object could be found as the evaluated script could create a callback during the `SerializeV8Object(result, responseArgList, 2, callbackRegistry);` call.
Browsers no object (sync & asnyc) has been registered will not hold a root object and therefore, no callback registry which would, prior to e9675a2c3e104405b15f4f9cad54778b0cc232a8, lead to an exception when the evaluted javascript source code …
=> Missing callback registry for browsers created without registered js objects

CefSharp.OffScreen/ChromiumWebBrowser.cs
There is a bug with the optional browser settings in the offscreen browser project which will lead to a null poiinter exception if no settings are available.
Example:
https://github.com/illfang/CefSharp/tree/offscreen-browser-browser-settings-nullptr-test
```
System.NullReferenceException: Object reference not set to an instance of an object.
at CefSharp.BrowserSettings.get_OffScreenTransparentBackground()
at CefSharp.ManagedCefBrowserAdapter.CreateOffscreenBrowser(IntPtr windowHandle, BrowserSettings browserSettings, RequestContext requestContext, String address)
at CefSharp.OffScreen.ChromiumWebBrowser.CreateBrowser(IntPtr windowHandle, String address, BrowserSettings browserSettings, RequestContext requestcontext)
at CefSharp.OffScreen.ChromiumWebBrowser..ctor(String address, …
```
=> Fix offscreen browser browser settings nullptr (breaking current interface)

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp
The promise creator function in the CefAppUnmanagedWrapper constructs an object which is not really required.
This minor PR reduces the created objects from 2 to 1 for every asynchronous method call.
=> Feature optimized promise creation

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.Core/Internals/StringUtils.h, CefSharp.Example/ExceptionTestBoundObject.cs, CefSharp.Example/Resources/ExceptionTest.html
- added a test case for logging JavaScript exceptions created in a Callback
- added a CreateExceptionString to the StringUtils for creating a verbose message for Javascript exceptions including the message, filename, line number and column; this methods also checks if the exception is available
- use the util function in the app unmanaged wrapper to create the JS exception string for callbacks and js evaluations, by this the `if (exception.get())` will now also be executed in both cases.
New log message (ExceptionTest.html)
```
Uncaught Callback Error (This callback from C# was delayed 500ms)
@ custom://cefsharp/ExceptionTest.html:59:20
```
Previous message
```
Uncaught Callback Error (This callback from C# was delayed 500ms)
```
=> Feature sanitized and verbose js exception strings

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.BrowserSubprocess.Core/JavascriptRootObjectWrapper.cpp, CefSharp.BrowserSubprocess.Core/JavascriptRootObjectWrapper.h
This PR is an addition to the commit 00c926a4cc66d5ae5ed0a4c25c7b933c358e7224 for solving #1354
In the previous commit, a new root object will be created during the `OnProcessMessageReceived` when there has not yet been a JS context created by the browser. By evanluating JS in the `OnProcessMessageReceived` function, a context will be created and `OnContextCreated` will be called.
As the root object has already been created the following will be the case:
```
LOG(WARNING) << "A context has been created for the same browser / frame without context released called previously";
```
This will skip the `Bind` of the root object to this new context which this PR tries to solve.
=> Fix ensure context binding of root object

CefSharp.Wpf/ChromiumWebBrowser.cs
Use RenderOptions of the control in Wpf ChromiumWebBrowser.cs CreateImage
This little change allows users to set the RenderOptions BitmapScalingMode for the ChromiumWebBrowser Wpf control just like this:
```
<cefSharp:ChromiumWebBrowser RenderOptions.BitmapScalingMode="Fant">
```
While NearestNeighbor (fixed value before my edit) looks fine if each rendered pixel is exactly displayed as a single pixel, using that setting for a browser placed in a viewport leads to ugly results.
You can test the different BitmapScalingMode settings for example in the Wpf.Example application if you set the RenderOptions.BitmapScalingMode property for the ChromiumWebBrowser in BrowserTabView.xaml.
Just change the Angel (Tweak WPF Rendering) of the browser in the running application to actually see the …
=> Allow User Specified RenderOptions (WPF)

CefSharp.WinForms/Internals/ControlExtensions.cs, CefSharp.WinForms/Internals/ParentFormMessageInterceptor.cs, CefSharp.Wpf.Example/Controls/NonReloadingTabControl.cs, CefSharp/DependencyChecker.cs, CefSharp/DisposableResource.cs, CefSharp/IBrowser.cs, CefSharp/IContextMenuHandler.cs, CefSharp/IDisplayHandler.cs, CefSharp/IDragData.cs, CefSharp/IFrame.cs, CefSharp/IMenuModel.cs, CefSharp/Internals/IntPtrExtensions.cs, CefSharp/ResourceHandler.cs, CefSharp/WebBrowserExtensions.cs
When I updated to *45.0.0-pre01* my not so forgiving StyleCop rules notified me of a missing parameter comment in the method *IContextMenuHandler.RunContextMenu*.
I did a quick search for some more empty XML comments and added them when necessary.
This fixes some warnings from #1162.
=> Add missing XML documentation comments

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.BrowserSubprocess.Core/Serialization/V8Serialization.cpp, CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/JavascriptCallbackProxy.cpp, CefSharp.Core/Internals/Serialization/JsObjectsSerialization.cpp, CefSharp.Core/Internals/Serialization/V8Serialization.cpp, CefSharp.Core/Internals/Serialization/V8Serialization.h, CefSharp.Example/BoundObject.cs, CefSharp.Example/CallbackResponseStruct.cs, CefSharp.Example/CefSharp.Example.csproj, CefSharp.Example/Resources/BindingTest.html
Resolves #1407
More the DeserializeV8Object call to within the `context->Enter` so a V8Object can be created
Change callback to use a struct as it's return type to demo the solution to this bug
Add missing list->SetDictionary call in V8Serialization.cpp
=> Add Support for executing a JavascriptCallback with a Struct as a param

CefSharp/Properties/AssemblyInfo.cs, build.ps1
This fixes #849, by providing a "reasonably official" CefSharp build that works correctly on Windows Server 2003 R2. Windows XP is untested, please report if it works or not.
Note: This changes the prerequisite from Visual C++ 2012 Redistributable to Visual C++ **2013** redistributable.
I have built versin 37.0.3 using this PR, and pushed it to NuGet (apart from the OffScreen package where I did not have publish rights, @amaitland :smirk:).
Merging.
=> Adjustments to make it possible to build CefSharp v37 using VS2013:

README.md
Also removed link to CefSharp v1. It's so outdated these days that there's no reason even linking to it. It was an important part of getting the project started, but... let's kill it now.
=> Adjusted details about CefSharp v37 (requiring VC++ 2013 redist)

CefSharp.Core/Internals/CefBrowserHostWrapper.cpp, CefSharp.Core/Internals/CefBrowserHostWrapper.h, CefSharp.Core/Internals/Serialization/ObjectsSerialization.cpp, CefSharp.Core/Internals/Serialization/ObjectsSerialization.h, CefSharp.Core/Internals/Serialization/Primitives.cpp, CefSharp.Core/Internals/Serialization/Primitives.h, CefSharp.Core/Internals/Serialization/V8Serialization.cpp, CefSharp.Core/Internals/Serialization/V8Serialization.h, CefSharp.Core/Internals/TypeConversion.h, CefSharp.Core/RequestContext.h, CefSharp.OffScreen.Example/Program.cs, CefSharp/CefSharp.csproj, CefSharp/IBrowserHost.cs, CefSharp/IRequestContext.cs
Add new Get/Set preference methods to the RequestContext
Implementation is not quite complete yet.
=> Implement Change Preferences at Runtime.

CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs, CefSharp.Wpf/ChromiumWebBrowser.cs
Port Touch Scroll changes from https://github.com/amaitland/CefSharp/commit/d854551a90e55c917a80d60bc67cf641f2f02d9b#diff-bfec65df46ec49f4ed79472147689599R1523
Untested changes, so they likely don't work as I've ported them from a much older branch.
Resolves #975
=> Implement WPF Touch Scroll

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.h, CefSharp.BrowserSubprocess.Core/CefAppWrapper.h, CefSharp.Core/CefSettings.h, CefSharp.Core/Internals/CefSharpApp.h, CefSharp.Example/CefExample.cs, CefSharp/Internals/CefSharpArguments.cs
Change from EnableFocusedNodeChanged to FocusedNodeChangedEnabled to match the existing WindowlessRenderingEnabled setting property.
=> Rename EnableFocusedNodeChanged to FocusedNodeChangedEnabled

CefSharp.Wpf/Internals/WpfExtensions.cs
There was a problem with the previous implementation. It worked correctly for many use cases:
- Dragging from a web app to a WPF control.
- Dragging from a WPF control to a web app.
- Dragging _html content_ from a web app to an input field
**But**: when dragging text from one input field to another, the text would vanish (!) when you drop it.
We debugged this here quite extensively. It turned out that if you have _set_ the `FragmentHtml` (even though you've set it to an empty string), it behaves like this. The solution is to avoid setting it if it is empty.
Merging so I can make a v47.0.1 with this included. @amaitland, do you want the PR towards the `master` branch also?
=> Added support for drag & drop from input fields

CefSharp.Core/Internals/ClientAdapter.cpp
set **returnNullIfBrowserNotFound** field value as "**true**" for **GetBrowserWrapper** method in **OnBeforeResourceLoad** in order to prevent crashing popup window, when popup window is closed.
=> Change method parameter value to prevent popup window crashing.

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/ResourceHandlerWrapper.cpp, CefSharp.Core/ResourceHandlerWrapper.h, CefSharp.Core/SchemeHandlerFactoryWrapper.h, CefSharp.Example/CefSharpSchemeHandler.cs, CefSharp.Example/FlashResourceHandler.cs, CefSharp/IResourceHandler.cs, CefSharp/ResourceHandler.cs
Expose all methods of CefResourceHandler - Resolves #1592
Previously we were passing in the frame, request wrappers which hadn't been used, so just keep things simple and remove the code.
Current users should extend ResourceHandler instead of IResourceHandler and add the override keyword
=> Rewrite IResourceHandler - Expose all methods

CefSharp.WinForms/CefSharp.WinForms.csproj, CefSharp.Wpf/CefSharp.Wpf.csproj, NuGet/CefSharp.Common.nuspec, NuGet/CefSharp.OffScreen.nuspec, NuGet/CefSharp.WinForms.nuspec, NuGet/CefSharp.Wpf.nuspec, appveyor.yml, build.ps1
Add pdb files to nuspec - they're only included when the -symbol flag is used
Add src files to nuspec - they're only included when the -symbol flag is used
Update appveyor.yml to push symbol packages to the MyGet feed
Add -symbol flag to build.ps1 so the symbol packages are generated
WinForms project not outputs pdb files
WinForms release builds are not optimized - probably should have been already
Unfortunately this will need to be merged into `master` to test fully. The packages build locally, so hopefully they'll appears on the `MyGet` feed shrotly.
=> Publish Symbol Packages

CefSharp.Example/BoundObject.cs, CefSharp.Example/Resources/BindingTest.html, CefSharp.Example/Resources/Home.html, CefSharp.Example/ScriptedMethodsBoundObject.cs, CefSharp/CefSharp.csproj, CefSharp/Internals/JavascriptMethod.cs, CefSharp/Internals/JavascriptObjectRepository.cs, CefSharp/Internals/MethodParameter.cs, NuGet.config
This fix allow you to use a params array for a parameter in your C# object that is bound to your javascript functions.
=> Add paramArray support to Javascript Binding

CefSharp.Core/Internals/ClientAdapter.cpp
Changed the returnNullIfBrowserNotFound parameter to true for some calls to GetBrowserWrapper() to prevent exceptions when closing a popup window.
Replacing pull request 1658 - targeting against master.
=> Issue 1594 - Updated calls to GetBrowserWrapper()

CefSharp/Internals/JavascriptObjectRepository.cs
Fix Issue #1582, Use ToLowerInvariant while converting Javascript Function names to camelCase
=> Fix Issue #1582, Use ToLowerInvariant while converting Javascript Function names to camelCase

CefSharp.BrowserSubprocess/CefSharp.BrowserSubprocess.csproj
Access Violation of BEX or APPCRASH occurrs on Windows Server 2008 R2 with Terminal Service
Hi,
I have AppCrash with CefSharpSubProcess in Windows Server 2008 R2 with Terminal Service.
I can not disable Data Execution Prevention (DEP) for CefSharpSubProcess.exe.
I have this message : " the execution of data protection must be activated to execute this program. You can not disable the protection of data execution for this program."
I think to activate TSAWARE for CefSharpSubprocess.exe. See : https://support.microsoft.com/en-us/kb/2279689 
Option 3
Thanks
=> Windows Server 2008 R2 TerminalServices BEX Access Violation

CefSharp.Example/Filters/FindReplaceMultiResponseFilter.cs
You create multiple search-and-replace queries to filter content on-the-fly, the only caveat is that you need to make sure that your queries are in chronological order since the stream doesn't rewind.  Useful for tweaking JavaScripts on remote servers.
=> Add FindReplaceMultiResponseFilter Example

CefSharp/WebBrowserExtensions.cs
Tested by running:
```
ExecuteScriptAsync("window.runtest", "hello", "quote'abc", -3000000, 5.5, 8F, 7.66D, true, false, null);
```
window.runtest prints out all arguments and their type.
Old output on most european systems, note booleans and decimal numbers:
```
hello | string
(syntax error due to unescaped quote)
-3000000 | number
5 | number
5 | number
8 | number
7 | number
66 | number
True | string
False | string
null | object
```
New output:
```
hello | string
quote'abc | string
-3000000 | number
5.5 | number
8 | number
7.66 | number
true | boolean
false | boolean
null | object
```
Closes #1728.
=> Fix bool, number culture, and string escaping in ExecuteScriptAsync with parameters

CefSharp.BrowserSubprocess.Core/JavascriptMethodHandler.cpp, CefSharp.BrowserSubprocess.Core/JavascriptPropertyHandler.h, CefSharp.BrowserSubprocess.Core/TypeUtils.cpp, CefSharp.BrowserSubprocess.Core/TypeUtils.h, CefSharp.Example/BoundObject.cs, CefSharp.Example/Resources/BindingTest.html
I added support to use anonymous function as callback inside an object.
So it is possible to do next:
```javascript
bound.testCallbackFromObject({
foo: "bar",
callback: function(text) {
console.log(text);
}
});
```
It is possible to merge this feature to the project?
This is my first pull request :)
=> anonymous function callback inside an object parameter

CefSharp.OffScreen/CefSharp.OffScreen.csproj, CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.OffScreen/PopupBlending.cs
Created to have the possibility to merge the dropdown list (select tag) popup menu with the full browser to get one single bitmap containing the whole page.
There are two commits :
-  4078663 : Simply improve what can be overriden and implement a few functions for the popup informations.  This allows a better local implementation of the InvokeRenderAsync function.
-  b20ddb7 : Implementation of a InvokeRenderAsync which does the blending of popup/background image. Added a configuration to know between split and merge of the background image and popup. Also modified what happens on popup opening/closing to match the rest of the modifications.
First review contributor : ejerome
No issue opened as seen with amaitland on Gitter.
=> Offscreen popup (dropdown list) merge with the background browser.

CefSharp/WebBrowserExtensions.cs
Added two overloads for EvaluateScriptAsync to provide the option to pass in methodName and args instead of the string representation of the Javascript. Two overloads were needed because EvaluateScriptAsync already used an optional parameter, so it wouldn't be possible to mix both optional parameters and params in the same signature without forcing the callers to always use named parameters.
=> Add overloads for EvaluateScriptAsync to support methodName and args

CefSharp.WinForms.Example/Handlers/LifeSpanHandler.cs, CefSharp.WinForms/ChromiumWebBrowser.cs
- Make it so that closing a tab in the WinForms example does not close the
entire application. We need to make sure that the LifeSpanHandler is
still around when `managedCefBrowserAdapter` is disposed since it is
going to call `CloseBrowser`. That way, we can implement LifeSpanHandler
and reject closing the entire application as described in #1574
=> Fix LifeSpanHandler not Called During Dispose

NuGet/CefSharp.Common.targets, NuGet/CefSharp.OffScreen.targets, NuGet/CefSharp.WinForms.targets, NuGet/CefSharp.Wpf.targets
During build process msbuild copies CefSharp files to `$(TargetDir)`
Sometimes it is not suitable, and instead of override `$(TargetDir)` globally another property has been introduced. It's name is `$(CefSharpTargetDir)`
It is possible to override this property in `csproj` file
```xml
<PropertyGroup>
<CefSharpTargetDir>C:\MyProjectOutDir\Cef</CefSharpTargetDir>
</PropertyGroup>
```
If this property should depend on `$(TargetDir)` don't forget to override property after importing `Microsoft.CSharp.targets` (`$(TargetDir)` is defined there)
```xml
<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
<PropertyGroup>
<CefSharpTargetDir>$(TargetDir)\Cef</CefSharpTargetDir>
</PropertyGroup>
```
Also, `$(TargetDir)` is used by default if `$(CefSharpTargetDir)` was not specified in …
=> Configure directory where msbuild will copy CefSharp files

CefSharp.Core/SchemeHandlerFactoryWrapper.h
Regression in 49.0 release.  Prevented use of default CEF handler when
using a custom scheme handler.
=> Fix NRE when returning null from a scheme handler factory

.gitignore, CefSharp.Core/Internals/TypeConversion.h, CefSharp.Example/CefExample.cs, CefSharp.Example/DownloadHandler.cs, CefSharp.Wpf.Example/MainWindow.xaml, CefSharp.Wpf.Example/MainWindow.xaml.cs, CefSharp.Wpf.Example/ViewModels/BrowserTabViewModel.cs, CefSharp.Wpf.Example/Views/BrowserTabView.xaml, CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs, CefSharp/DownloadItem.cs
This property is very valuable and I need it in the project I am working on right now!
Also:
Added a sidebar to the example app which shows the DownloadItems as received by CefSharp.Core/Internals/TypeConversion.h
Added a View menu for hiding/showing the regular sidebar and the new download info sidebar.
=> Added DownloadItem .OriginalUrl

CefSharp.Wpf/ChromiumWebBrowser.cs
A little touchup to better explain some of the event handlers.
=> Humanify the ghostdoc comments

README.md
Updated: Line 39 fixed the link to go to the alternative method. 
Additonally, I added around line 40, a explaination on how to view all forks of Cefsharp. This will solve the Issue  #1904
=> See Full Desc. Fixes Forks Display.

CefSharp.Wpf/ChromiumWebBrowser.cs
See https://github.com/cefsharp/CefSharp/issues/1889#issuecomment-281741492
- Made GetViewRect always round up to prevent the image from being smaller than the control
=> WPF - Made GetViewRect always round up

CefSharp.Wpf/ChromiumWebBrowser.cs
This commit is an attempt to fix the bug mentioned in this issue:
https://github.com/cefsharp/CefSharp/issues/1723
I modeled this change after the way the WPF ComboBox captures the mouse by looking at the code on referencesource.microsoft.com.  It needs further testing to verify it doesn't break other stuff, hoping to get some more testing from one of my users tomorrow, wanted to start the conversation.
=> WPF Moved capture into Opened/Closed events for Popup

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.Example/AsyncBoundObject.cs, CefSharp.Example/Resources/BindingTest.html, CefSharp/Internals/JavascriptObjectRepository.cs
**Problem:**
It was not possible to call .Net methods from JS that return arrays of structs.
Fix:
IsComplexType from JavascriptObjectRepository returns false for arrays.
Notes:
This PR requires [1979](https://github.com/cefsharp/CefSharp/pull/1979)
=> Allow calling managed methods from objects bound with RegisterAsyncJsObject that return arrays of structs

CefSharp.Wpf/ChromiumWebBrowser.cs
=> Added minimal WPF designer support

CefSharp/DefaultResourceHandlerFactory.cs
Changed from `Uri.ToString` to `Uri.AbsoluteUri`
`Uri.ToString` returns a human-readable URL which isn't encoded, this causes the `Key` in the `ConcurrentDictionary` to not match the Url from `request.Url` in `GetResourceHandler`
=> Changed from Uri.ToString to Uri.AbsoluteUri

CefSharp.Core/Internals/CefBrowserHostWrapper.cpp, CefSharp/PdfPrintSettings.cs
This connects up the PDF scaling however it doesn't seem to scale the PDF. So I think the key used to scale the PDF in CEF maybe wrong.
=> Added support for PDF scaling

CefSharp/CefSharp.csproj, CefSharp/DefaultResourceHandlerFactory.cs, CefSharp/ResourceFactoryItem.cs, CefSharp/WebBrowserExtensions.cs
- Added a `ResourceFactoryItem` class
- Added a overload to `RegisterHandler` that takes a bool representing whether or not the handler should be used only once
- Made `GetResourceHandler` remove the `ResourceFactoryItem` if it was specified as a `one-time use` handler
- Made LoadHtml register a `one-time use` handler
=> Made it possible to register a "one-time use" ResourceHandler

README.md
Hello.
I was unsure if a small fix like this requires an issue. Please tell me if I have to create one.
The table with cefsharp versions contains an error: CefSharp 37 needs VC++ Redist version 2012, not 2013.
I've verified this on Windows 7 and Windows Server 2012 r2.
=> Update Readme with correct version of VC++ Version

README.md
Personally I find 3 the same badges confusing. So I changed the labels: 
before:
after:
=> change labels of badges

CefSharp.Wpf/ChromiumWebBrowser.cs
Fix for #2106.
Checks that the visual is connected to a presentation source before calling PointToScreen()
Updates the browserScreenLocation value when the presentation source changes
Fix compiler warning for XML comment
=> Prevent unhandled exception in PointToScreen when not yet visible

NuGet/CefSharp.Common.props, NuGet/CefSharp.OffScreen.props, NuGet/CefSharp.WinForms.props, NuGet/CefSharp.Wpf.props
Realized I should create pr on master. Sorry about that.
I'm also having the same issue as @joaompneves with Visual Studio rebuilding every time projects that depend on CefSharp and use AnyCPU platform are built. I opened Issue #2077 to add more details and repro steps.
I took @joaompneves' PR #2067 that fixes this issue and applied it to all the other .props files so that the issue is fixed for all references (common, core, Wpf, WinForms, OffScreen).
I hope this helps,
=> Prevent VS from always rebuilding projects that reference CefSharp when using AnyCPU platform, All .props files

CefSharp.Core/Internals/TypeConversion.h
The NameValueCollection auto merges (according to MSDN) all the values under the same key, with ",".
This breaks some headers, like the "Set-Cookie"; where the "." has another meanings according to RFC.
as far as i've seen, this issue will be present everytime a customhandler is used.
=> Pevent merging of repeated values in headerMap when using custom handlers

CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj, CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj.filters, CefSharp.BrowserSubprocess.Core/Resource.rc, CefSharp.BrowserSubprocess.Core/packages.config, CefSharp.BrowserSubprocess/app.manifest, CefSharp.Core/CefSharp.Core.vcxproj, CefSharp.Core/CefSharp.Core.vcxproj.filters, CefSharp.Core/Internals/CefBrowserHostWrapper.cpp, CefSharp.Core/ManagedCefBrowserAdapter.cpp, CefSharp.Core/Resource.rc, CefSharp.Core/WindowInfo.h, CefSharp.Core/packages.config, CefSharp.OffScreen.Example/CefSharp.OffScreen.Example.csproj, CefSharp.OffScreen.Example/app.manifest, CefSharp.OffScreen.Example/packages.config, CefSharp.WinForms.Example/CefSharp.WinForms.Example.csproj, CefSharp.WinForms.Example/app.manifest, CefSharp.WinForms.Example/packages.config, CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj, CefSharp.Wpf.Example/app.manifest, CefSharp.Wpf.Example/packages.config, CefSharp/IWindowInfo.cs, CefSharp/Properties/AssemblyInfo.cs, build.ps1
Note that there is one breaking change as offscreen windows are now automatically transparent due to this cef change: https://bitbucket.org/chromiumembedded/cef/commits/3f71138d64586d774f645a6db5283b5205ea9df4
To make a offscreen window non-transparent you need to set the background colour as shown below were it is set to white:
browserSettings.BackgroundColor = 0255255255;
=> Update to Cef Version 59.0.0

CefSharp.BrowserSubprocess/CefSharp.BrowserSubprocess.csproj, CefSharp.props, CefSharp3.ChildProcessDbgSettings, build.ps1
note: I redid the pull request for a more clean version.
Added support for VS2017, using the VS2015 toolset (use the VS2017 installer to install this toolset).
I also added a config file for the "Microsoft Child Process Debugging Power Tool" which will allow automatic debugging of child processes.
I updated the nuget url, since appveyor could not install xunit.abstractions 2.0.1 with the old nuget.
I extracted the PostBuild script into the CefSharp.props file and tried to keep the behaviour the same for non-VS2017 (however, I cannot test that without VS2013 and VS2015, but it succeeds on appveyor).
Note though that the CefSharp.Test OffScreenBrowserBasicFacts tests are failing and I am unsure if that is expected (since they were only recently added and I don't see a succesfull appveyor …
=> VS2017 build support (using the VS2015 tooling)

NuGet/CefSharp.Common.targets
When the copying of files is done after build and you sign a clickonce distribution the copied files will not match the manifests hash anymore.
Changing it to BeforeBuild got it working again for me.
=> Change the targets to BeforeBuild

CefSharp.WinForms/ChromiumWebBrowser.cs
This PR solves the issue described in https://github.com/cefsharp/CefSharp/issues/2206#issuecomment-362769476
The changes in this PR prevents the designer from setting the default value of specific properties which caused it to attempt to load `CefSharp.Core` causing an exception to be thrown
=> WinForms: Prevent designer from setting default values

CefSharp.Wpf.Example/Handlers/LifespanHandler.cs
I want to have my own Window (styled) for the CefSharp popups. So, I've copied the `LifespanHandler` and uncommented the code to my app. I've got a rare crash from my users that browser is disposed in the `OnAfterCreated` method.
=> Example LifespanHandler.OnAfterCreated fix eperimental code rare crash

CefSharp.Core/Internals/Serialization/V8Serialization.cpp, CefSharp.Core/Internals/Serialization/V8Serialization.h
Fixes #2370.
Also rename the local from `seen` to `ancestors` as it is not the set of all seen objects, just those in the chain from current to root.
Added a brief comment to this effect.
In issue 2370 I missed the call to `Pop` and thought this collection had _every_ seen object in it which could be quite bad for performance when calling `Contains`. Given it actually only contains ancestors I doubt the perf gain here is considerable, and I confess that I haven't benchmarked.
I almost didn't file this PR. Feel free to close it. I won't mind.
=> V8Serialization - Replace usage of Stack with HashSet

CefSharp.Core/Internals/RenderClientAdapter.h
Popup Elements (e.g. combobox dropdowns) appear in wrong screen locations due to wrong order of parameters in Rect constructor (e.g. x/y and w/h are swapped). 
Bug has been introduced with this commit: 
https://github.com/cefsharp/CefSharp/commit/c1b89c62e967dcc24662887b4b31519c69636614#diff-abed174f3903eb62b98999938e4f67d0R108
Branch cefsharp/65 is affected, too.
=> OnPopupSize - fix incorrect ordering of Rect params

CefSharp.Core/Internals/Serialization/V8Serialization.cpp, CefSharp.Example/AsyncBoundObject.cs, CefSharp.Example/Resources/BindingTest.html
#2392 
Handle any enumarable, not just arrays when serializing (e.g. when calling
`IJavascriptCallback.ExecuteAsync`).
Otherwise, `System.Reflection.TargetParameterCountException` is thrown during serialization
=> Serialize any Enumerable (List<T>) type to V8 object properly

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Example/TempFileDialogHandler.cs, CefSharp/CefSharp.csproj, CefSharp/Enums/CefFileDialogFlags.cs, CefSharp/Enums/CefFileDialogMode.cs, CefSharp/Handler/IDialogHandler.cs
Resolves #2277 by splitting the enum.
In CEF, `cef_file_dialog_mode_t` is a mix of flags and non-flags. In the .NET managed world, a combination like that rather unusual. As such, my suggestion is to split the enum into `CefFileDialogMode` and `CefFileDialogFlags`.
=> Split CefFileDialogMode into CefFileDialogMode and CefFileDialogFlags

CefSharp.Core/Internals/Serialization/V8Serialization.cpp
> The approved types for an enum are byte, sbyte, short, ushort, int, uint, long, or ulong.
[enum keyword (C# Reference) | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/enum)
So, all enums can be serialized like byte~ulong types.
=> Enum serialization added to V8Serialization.cpp

CefSharp/WebBrowserExtensions.cs
- Added a `IsNumeric` function that checks if a given object is numerical (sbyte, byte, short, ushort, int, uint, long, ulong, float, double, decimal)
- Removed the `numberTypes` array
=> WebBrowserExtensions::GetScript - Added support for all numerical types

CefSharp.Wpf/ChromiumWebBrowser.cs
- Use `nameof` when registering a `DependencyProperty` instead of a hardcoded string for the property name
This has no effect on the build output, `nameof(x)` is replaced with `"x"` at compile time
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/nameof
=> WPF - Use nameof for DependencyProperty.Register instead of hardcoded strings

CefSharp.WinForms/ChromiumWebBrowser.cs
- Added a missing `Browsable(false)` attribute on the property `JavascriptObjectRepository`
- Updated the `DefaultValue` attribute on the property `UseParentFormMessageInterceptor`
=> WinForms - Added missing Browsable attribute on JavascriptObjectRepository + Updated DefaultValue attribute on UseParentFormMessageInterceptor

CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj, CefSharp.Core/CefSharp.Core.vcxproj
- Enabled MultiProcessorCompilation for `CefSharp.Core` and `CefSharp.BrowserSubprocess.Core`
Compile time before:
```
CefSharp.Core: 00:00:16.87
CefSharp.BrowserSubprocess.Core: 00:00:10.40
Total: 00:00:27.27
```
Compile time after:
```
CefSharp.Core: 00:00:09.98
CefSharp.BrowserSubprocess.Core: 00:00:07.67
Total: 00:00:17.65
```
=> Enabled MultiProcessorCompilation for Core and BrowserSubprocess.Core

CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj, CefSharp.Core/CefSharp.Core.vcxproj
- Added `SourcePath` for CEF files to `CefSharp.Core` and `CefSharp.BrowserSubprocess.Core`
Without this it compiles perfectly fine but `IntelliSense` doesn't suggest anything for CEF related types. They all show up as `error-type`.
=> Added SourcePath to CefSharp.Core and CefSharp.BrowserSubprocess.Core

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/CookieVisitor.cpp, CefSharp.Core/Internals/TypeConversion.h, CefSharp.Core/ResourceHandlerWrapper.cpp
- Moved conversion of `CefCookie` -> `Cookie` to `CefSharp.Core\Internals\TypeConversion.h`
- Copied `ConvertCefTimeToDateTime` from `CefSharp.BrowserSubprocess.Core\TypeUtils.h` to `CefSharp.Core\Internals\TypeConversion.h` as including the file caused errors
The conversion of cookies was duplicated in
- `CefSharp.Core\Internals\ClientAdapter.cpp`
- `CefSharp.Core\Internals\CookieVisitor.cpp`
- `CefSharp.Core\ResourceHandlerWrapper.cpp`
=> Refactoring - Move CefCookie conversion to TypeConversion

CefSharp.Core/Cef.h
Resolves #2600 
- Added initialized check to `GetGlobalCookieManager`, `GetGlobalRequestContext`, `GetBlockingCookieManager`, and `GetPlugins`
The reason a macro was used instead of a function is so that the exception can contain the method name.
Calling `Cef.GetGlobalCookieManager();` before `Cef.Initialize()` causes an exception with this message to be thrown: `CefSharp::Cef::GetGlobalCookieManager requires that CEF has been initialized first.`
=> Cef.Get* - Added initialize checks to Cef.Get* methods

CefSharp.Wpf/ChromiumWebBrowser.cs
- Renamed `private static bool designMode;` to `private static bool DesignMode;`
Visual studio didn't actually apply the EditorConfig rule about throwing errors until the file was opened so this violation was left alone for a while.
=> WPF - Fix compile error because of IDE1006 Naming rule violation

.editorconfig, CefSharp.BrowserSubprocess.Core/Resource.rc, CefSharp.Core/Resource.rc, CefSharp.shfbproj, CefSharp/Properties/AssemblyInfo.cs, LICENSE, NuGet/CefSharp.Common.nuspec, NuGet/CefSharp.OffScreen.nuspec, NuGet/CefSharp.WinForms.nuspec, NuGet/CefSharp.Wpf.nuspec, build.ps1
build.ps1 changes:
- Updates the version number in `CefSharp.shfbproj`
- Updates the version number in `appveyor.yml`
- Updates copyright year on compiled files to the current year, same as CEF does
- Specifies `utf-8` as the encoding when reading files
- Saves files as UTF-8 without BOM
- build.ps1 is now saved as `utf-8-bom`, otherwise it breaks on windows when containing non-ASCII characters (©)
Editorconfig:
- Specified `utf-8-bom` for `*.ps1` files
Maintenance:
- LICENSE: Removed the copyright year as it's not needed
- NuGet: Removed the copyright year on the `nuspec` files as it's not needed
Was going to make build.ps1 update the year on LICENSE and NuGet as well, but the years for NuGet were unnecessary and LICENSE should only change year when it's updated.
=> Build.ps1 - Automated more tasks relating to updating CefSharp version and copyright year

README.md
I've added SharpBrowser to the readme. The last time you mentioned that it was not using nuget, so I fixed that. Its now taking the latest version from nuget. I just included the `bin` directory in the repo because sometimes CefSharp has issues downloading all the needed assets. I've also updated to CefSharp 71 and .NET 4.6.
Could you consider it please?
=> Readme.md - Add SharpBrowser

CefSharp.WinForms.Example/BrowserTabUserControl.cs
- Made the `ChromeWidgetMessageInterceptor` set itself up again after a render process switch happens
Fixes #2579
=> Fixed message interceptor not working after a render process switch

CefSharp.Wpf/CefSharp.Wpf.csproj, CefSharp.Wpf/Rendering/AbstractRenderHandler.cs, CefSharp.Wpf/Rendering/Experimental/ByteArrayWritableBitmapRenderHandler.cs, CefSharp.Wpf/Rendering/Experimental/IncreaseBufferInteropRenderHandler.cs, CefSharp.Wpf/Rendering/InteropBitmapRenderHandler.cs, CefSharp.Wpf/Rendering/WritableBitmapRenderHandler.cs
- Added `AbstractRenderHandler` that takes care of the basics of a `IRenderHandler`
- Refactored the `RenderHandler`s to inherit from `AbstractRenderHandler`
- Implemented the correct and thread safe dispose pattern
=> WPF - Refactor RenderHandler implementations

CefSharp.Core/BrowserSettings.h
When a `BrowserSettings` object is created, it creates an instance of `CefBrowserSettings`, then when the `BrowserSettings` object is disposed/collected it never deletes the `CefBrowserSettings` instance meaning it leaks. This PR fixes that by deleting it when `BrowserSettings` is disposed/collected.
Before this change, creating and disposing `1 000 000` `BrowserSettings` objects caused the memory usage to climb to `337,71 MB`, after this change it goes to `99,32 MB`
=> Core - BrowserSettings: Fixed a memory leak

CefSharp.Core/WindowInfo.h
When a `WindowInfo` object is created, it creates an instance of `CefWindowInfo`, then when the `WindowInfo` object is disposed/collected it never deletes the `CefWindowInfo` instance meaning it leaks. This PR fixes that by deleting it when `WindowInfo` is disposed/collected.
Before this change, creating and disposing `1 000 000` `WindowInfo` objects caused the memory usage to climb to `130,58 MB`, after this change it goes to `99,32 MB`
=> Core - WindowInfo: Fixed a memory leak

CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.WinForms/ChromiumWebBrowser.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/IWebBrowser.cs
- Added an `IsDisposed` property to `IWebBrowser`
- Implemented a thread safe dispose pattern
- Now only disposes of managed objects when `disposing` is set to `true`
- Simplified the handling of design mode and disposing
Resolves #1954 
EDIT:
As this is getting merged in parts, here are the relevant commits
OffScreen: https://github.com/cefsharp/CefSharp/commit/58fac3865b46c0b55807f670298d0eb070a964ce https://github.com/cefsharp/CefSharp/commit/b1ef9e8bc2c55a5e0e9a0b66988f670695836177
=> Improved dispose pattern in ChromiumWebBrowser

CefSharp/IJavascriptObjectRepository.cs
=> Fixed spelling error in IJavascriptObjectRepository

CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.WinForms/ChromiumWebBrowser.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/Internals/InternalWebBrowserExtensions.cs
WinForms/Wpf/OffScreen - Reorder Dispose methods
- Set browser initialized to false
- Release event handlers
- Dispose managedCefBrowserAdapter
- Set handlers to null
Follow up to #2651
=> Reorder dispose pattern in ChromiumWebBrowser

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/ClientAdapter.h, CefSharp.Example/CefSharp.Example.csproj, CefSharp.Example/Handlers/AudioHandler.cs, CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.WinForms/ChromiumWebBrowser.cs, CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/CefSharp.csproj, CefSharp/Enums/ChannelLayout.cs, CefSharp/Handler/IAudioHandler.cs, CefSharp/IWebBrowser.cs
Initial implementation for #2714
Still some work required, this compiles, nothing past that so far. Still need to validate how to map `float**` to a `C#` type. One option would be to copy the data to a `byte[]` in native code, this implies the user is always going to want access to the data, and will have a perf implication if they don't.
The default pattern of `return this` in `ClientAdapter` has been used.
```
virtual DECL CefRefPtr<CefAudioHandler> GetAudioHandler() OVERRIDE { return this; }
```
Unfortunately this will always trigger the `Audio Mirroring` feature, which we don't want unless the user has explicitly provided an `IAudioHandler` implementation. So this will also need to be rewritten with a separate wrapper class.
https://bitbucket.org/chromiumembedded/cef/commits/9f41a27e58 …
=> Add IAudioHandler

CefSharp.Core/ManagedCefBrowserAdapter.cpp, CefSharp.Core/ManagedCefBrowserAdapter.h
When WCF is not used the System.ServiceModel assembly is not required. With this refactoring the runtime will avoid loading the assembly if WCF if not used.
Edit: My main motivation behind this change it to be able to use CefSharp with .NET Core 3.0. While in the long term it may be better to generate .NET Core specific assemblies, this change allows .NET Core which does not have System.ServiceModel to load the .NET Framework assemblies. As a side effect it also results in a slightly smaller memory footprint for .NET Framework applications that don't use WCF.
I have tested this change by using the NuGet packages (CefSharp.Common/CefSharp.WinForms generated using `build.ps1 vs2017`) and checking the loaded assemblies when running a program in Release mode. I've also tested it with a .NET …
=> Refactor to avoid loading System.ServiceModel assembly

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj, CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj.filters, CefSharp.BrowserSubprocess.Core/JavascriptPostMessageHandler.h, CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/Messaging/Messages.h, CefSharp.Example/CefExample.cs, CefSharp.Example/CefSharp.Example.csproj, CefSharp.Example/CefSharpSchemeHandlerFactory.cs, CefSharp.Example/PostMessage/PostMessageExample.cs, CefSharp.Example/PostMessage/PostMessageExampleData.cs, CefSharp.Example/Properties/Resources.Designer.cs, CefSharp.Example/Properties/Resources.resx, CefSharp.Example/Resources/PostMessageTest.html, CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.WinForms/ChromiumWebBrowser.cs, CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj, CefSharp.Wpf.Example/MainWindow.xaml, CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/CefSharp.csproj, CefSharp/Event/JavascriptMessageReceivedEventArgs.cs, CefSharp/IWebBrowser.cs, CefSharp/Internals/IWebBrowserInternal.cs
- JavascriptMessageReceived event added to ChromiumWebBrowser/IWebBrowser
- CefSharp.PostMessage and cefSharp.postMessage added to V8Context on creation for use in Javascript
Resolves https://github.com/cefsharp/CefSharp/issues/2775
=> Add CefSharp.PostMessage

CefSharp.Core/ManagedCefBrowserAdapter.cpp, CefSharp.Core/ManagedCefBrowserAdapter.h, CefSharp.Example/CefExample.cs, CefSharp.Example/CefSharp.Example.csproj, CefSharp.Example/CefSharpSchemeHandlerFactory.cs, CefSharp.Example/JavascriptBinding/AsyncBoundObject.cs, CefSharp.Example/Properties/Resources.Designer.cs, CefSharp.Example/Properties/Resources.resx, CefSharp.Example/Resources/BindingTestSingle.html, CefSharp.Example/Resources/BindingTestsAsyncTask.html, CefSharp.Test/CefSharp.Test.csproj, CefSharp.Test/Framework/ConcurrentMethodRunnerQueueFacts.cs, CefSharp.Wpf.Example/MainWindow.xaml, CefSharp.Wpf.Example/MainWindow.xaml.cs, CefSharp/CefSharp.csproj, CefSharp/Internals/ConcurrentMethodRunnerQueue.cs, CefSharp/Internals/IBrowserAdapter.cs, CefSharp/Internals/IMethodRunnerQueue.cs, CefSharp/Internals/MethodRunnerQueue.cs, CefSharp/Internals/ParallelMethodRunnerQueue.cs
Remove Concurrent Task execution code from MethodRunnerQueue
Add ConcurrentMethodRunnerQueue
- For the new code path the Func is executed, if the Result is a generic Task we wait for it's completion
- If the task is not generic then we return immediately
This is only enabled when CefSharpSettings.ConcurrentTaskExecution = true;
Additional tests will be required before this is production ready
Resolves #2758
=> Async JavascriptBinding - Add support for returning Task

CefSharp.WinForms/ChromiumWebBrowser.cs
**Summary:**
- When MultiThreaded message loop is disabled, we use the winform message loop. We want to ensure that Shift+Tab (cycle selection back) is recognized as a valid input by the browser control otherwise it breaks keyboard accessibility.
**Changes:** 
- I have added Shift + Tab to the list of inputs recognized by the browser.
I changed the winforms example and set MultiThreadedMessageLoop = false. Then I opened the webpage and tried shift + tab. The selection didn't cycle through the HTML content, instead it cycled through the WinForm controls.
Then, I added my change and redid the same steps as above. Shift + tab works fine. 
Note: I was looking at the original change to the code that I am modifying but couldn't find any automated tests that were written for it. I'd be happy to …
=> WinForms  - Add Shift+Tab to IsInputKey (used when MultiThreadedMessageLoop is disabled)

CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp.Wpf/Experimental/ChromiumWebBrowserWithTouchSupport.cs
**Summary:** 
- With #2745, touch and stylus can work.
- There're still a bug. Some operations may send duplicate events (like mousemove and touchmove when touch) , which cause bugs in some pages.
- Stylus pen can be improved. When use stylus pen, there will be many points in single event, and we can use all of them.
- With the help of my friend @walterlv, we fixed this bug and made this improvement.
**Changes:**
- Check if only mouse in all OnMouseXXX methods.
- Check if only stylus pen in all OnStylusXXX methods.
- Send all points to host in OnStylus.
- Fix comments. 
We have run the wpf example at Surface with mouse, touch and stylus pen. It works fine.
**Checklist:**
=> WPF - Fix and improve touch and stylus

CefSharp/PdfPrintSettings.cs
Fixes https://github.com/cefsharp/CefSharp/issues/2821 and https://github.com/cefsharp/CefSharp/issues/1808
**Summary:**
The comments on the `MarginX` (top, bottom, left, right) properties in `CefSharp.PdfPrintSettings` now properly reflect that they are measured in points, not mm.
**Changes:**
Changed comments on the `MarginX` properties in `CefSharp.PdfPrintSettings`
Created PDF from simple HTML using top margin of `0.5 * factor` and left margin of `1 * factor`
* When `factor` is 25.4 (millimeters per inch), the resulting PDF has margins that are visibly too small
* When `factor` is 72 (points per inch), the resulting PDF looks okay. Additionally, Adobe Acrobat Reader includes a measuring tool which snaps to corners and edges of objects. I used it to precisely measure the left and top …
=> PdfPrintSettings margin measured in points, not mm

CefSharp.Wpf/Themes/Generic.xaml
Fixes #2843
**Summary:**
- CefSharp Image Jumps Vertically on Height Change
**Changes:**
- Change canvas offset to Canvas.Top for PART_image in Generic.xaml
- I do not have a build environment for CefSharp set up, so I tested this by overriding the default template with the changes in this commit. So further testing may be needed
**Checklist:**
=> WPF - Use Canvas.Top="0" for PART_image absolute position.

CefSharp.Wpf/Rendering/AbstractRenderHandler.cs, CefSharp.Wpf/Rendering/Experimental/IncreaseBufferInteropRenderHandler.cs, CefSharp.Wpf/Rendering/InteropBitmapRenderHandler.cs, CefSharp.Wpf/Rendering/WritableBitmapRenderHandler.cs
Contributes to #2796
**Summary:**
- Fixed the `CopyMemory` entrypoint declaration, which is not working on .NET Core 3.0 as `kernel32.dll` doesn't have an `CopyMemory` export.
**Changes:**
- Changed `EntryPoint` from `CopyMemory` to `RtlCopyMemory`
- Changed the `numberOfBytes` parameter from `uint` to `UIntPtr`
Note: I believe using an pointer type (`IntPtr` or `UIntPtr`) for the `numberOfBytes` parameter is correct even though pinvoke.net (and other sites) specify it as `int`, because the documentation for [`CopyMemory`/`RtlCopyMemory`](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa366535%28v%3dvs.85%29) declares it as `SIZE_T` which is defined as pointer-sized integer (`ULONG_PTR`). Additionally, I have done some testing to verify that the value is …
=> WPF - Modify CopyMemory EntryPoint to work with .Net Core

NuGet/CefSharp.OffScreen.nuspec, NuGet/CefSharp.WinForms.nuspec, NuGet/CefSharp.Wpf.nuspec
Issue #2796
**Summary:** 
- Added a `.NETCoreApp3.0` dependency to the .nuspec files.
**Changes:**
- Added `<group targetFramework=".NETCoreApp3.0">` to `CefSharp.OffScreen.nuspec`, `CefSharp.WinForms.nuspec` and `CefSharp.Wpf.nuspec`.
This ensures the transitive dependencies (CefSharp.Common) will be resolved in .NET Core 3.0 projects, when adding only `CefSharp.WinForms`, `CefSharp.WPF` or `CefSharp.OffScreen` via `<PackageReference>`.
Tested by running `build.ps1`, and then using the built `.nupkg` packages (via local NuGet package source) in the `CefSharp.MinimalExample.NetCore.*` projects (see https://github.com/cefsharp/CefSharp.MinimalExample/pull/57) and removing the package reference to `CefSharp.Common`.
**Checklist:**
=> Add a ".NETCoreApp3.0" dependency to the .nuspec files

CefSharp.BrowserSubprocess.Core/BrowserSubprocessExecutable.h, CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj, CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj.filters, CefSharp.BrowserSubprocess.Core/WcfBrowserSubprocessExecutable.h, CefSharp.BrowserSubprocess/Program.cs, CefSharp/CefSharp.csproj, CefSharp/Internals/ParentProcessMonitor.cs
Issue #2796
**Summary:**
Refactor the BrowserSubProcess so the core of it's implementation in `CefSharp.BrowserSubprocess.Core`.
**Changes:** 
- Added `BrowserSubprocessExecutable` for use with .Net Core (no WCF)
- Added `WcfBrowserSubprocessExecutable` for use with the existing CefSharp.BrowserSubprocess.exe which supports WCF (conditionally)
- The `Javascript Binding` tests pass (both async and sync)
- `Eval` or javascript happens correctly
**Checklist:**
**TODO**
=> BrowserSubprocess - Refactor to support .Net Core

.vsconfig, CefSharp.props, build.ps1
Bumped sdk to 18362 CEF 77 now requires that version but we could lower it is desired.
Does not default to building with it.
Resolves #2628
=> Add support for compiling with Visual studio 2019

README.md
Not sure you want to remove the other options to really funnel it all to GH or not, but if not this at least prioritized GH.
Dislike doing two items in one merge but as they would likely conflict if they were submitted at the same time and it is just removing a sample project from the readme it's your call.  I couldn't find any new home for the HTMLView project.
=> Updated funding source information for new GH sponsors. Removed a project link that is dead.

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.BrowserSubprocess.Core/RegisterBoundObjectHandler.h, CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/TypeConversion.h
**Summary:**
Fixing C6246  warnings. Some examples are:
- Warning	C6246	Local declaration of 'frame' hides declaration of the same name in outer scope. For additional information, see previous declaration at line '234' of 'cefsharp.browsersubprocess.core\cefappunmanagedwrapper.cpp'.
- Warning	C6246	Local declaration of 'name' hides declaration of the same name in outer scope. For additional information, see previous declaration at line '299' of 'cefsharp.browsersubprocess.core\cefappunmanagedwrapper.cpp'.
- Warning	C6246	Local declaration of 'global' hides declaration of the same name in outer scope. For additional information, see previous declaration at line '45' of 'cefsharp.browsersubprocess.core\registerboundobjecthandler.h'.
These warning are frequently flagged by our build system, …
=> Fix all C6246 warnings: Local declaration hides declaration of the same name in outer scope.

CefSharp.Wpf/Experimental/WpfIMEKeyboardHandler.cs
Fixes [issue-number] 
- (Partially) fixes #1262
- I have added a small code to WpfImeKeyboardHandler.cs to address a Hangul character (Korean alphabet) is not emitting to the current input box after a Hangul is composed by IME. In other words, a user cannot make a word or a sentence using Korean IME because every time a single character is composed, it disappears and start 'composing' mode all over again.
- According to my inspection, it seems that Korean IME keeps producing characters while IME is in IME_COMPOSITION mode even before IME_ENDCOMPOSITION is sent. It is like laying eggs while a chicken is walking. Current approach to IME implemented in CefSharp.Wpf seems that in order to "finalize" composing a text, …
=> WPF - IME Fix Korean character emitting issue

CefSharp.OffScreen.Example/Program.cs
**Summary:** 
- The google search input element wasn't found in javascript code. `"Uncaught TypeError: Cannot set property 'value' of null", source: about:blank (1)`
Executed OffScreen sample and looked at the resulting screenshot and console output.
Before:
After:
**Checklist:**
=> OffScreen Example - Update Javascript to reflect google change

CefSharp/DomNode.cs
**Summary:**
- The code style in `DomNode` does not comply with `.editorconfig` which showed up in vs 2019 (16.4.5) as an error.
https://github.com/cefsharp/CefSharp/blob/7100c3d0ec645b7b12e0b0bee5a8a0de3c998812/.editorconfig#L44
**Checklist:**
=> Core - DomNode consistent code style

CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj
**Summary:**
- remove project reference to CefSharp.BrowserSubprocess for consistency. a solution dependency does already exists.
https://github.com/cefsharp/CefSharp/blob/749ec15972d332ce0fc59f3785184f884df748ae/CefSharp3.sln#L9-L12
**Changes:**
- see https://github.com/cefsharp/CefSharp/pull/3065#discussion_r385986521 and https://github.com/cefsharp/CefSharp/pull/3065#discussion_r385990844
**Checklist:**
=> Remove project reference to CefSharp.BrowserSubprocess for consistency

CefSharp.Test/CefSharp.Test.csproj, CefSharp.Test/CefSharpFixture.cs, CefSharp.Test/packages.config
**Summary:**
- Ensure that `Cef.Shutdown` is called on the same thread as `Cef.Initialize` in tests
**Changes:**
- `Cef.Shutdown` wasn't called on the same thread but the exception didn't showed up in tests because it was called asynchron in a sync `Dispose` method.
- The first commit shows the bug by implementing the async dispose from xunit. Here is a test which shows the exception: https://ci.appveyor.com/project/campersau/cefsharp/builds/31148092#L374
I also observed it when debugging tests in VS 2019.
- The second commit fixes the problem by making sure that these methods get called on the same thread.
https://ci.appveyor.com/project/campersau/cefsharp/builds/31148152
**Checklist:**
=> Test - Call Cef.Shutdown on same thread as Cef.Initialize

CefSharp.Core/Internals/CefBrowserHostWrapper.cpp
**Fixes:** #3104 
**Summary:** 
- AltGr support added.
**Changes:**
- copied and adjusted code from linked cef commit
- started CefSharp.Wpf.Example
- navigated to https://jsfiddle.net
- typed the following characters into the CSS text field using a german keyboard layout
`{@[³²\~]}µ`
All these characters requiring AltGr modifier on german keyboard. None of them worked before the fix.
**Checklist:**
=> WPF - Implement AltGr support.

CefSharp.Wpf/Experimental/WpfIMEKeyboardHandler.cs
**Issue:**
#1262
**Summary:** 
- This pr is based on pull request [WPF - IME Fix Korean character emitting issue](https://github.com/cefsharp/CefSharp/pull/3054). I find out that only ImeNative.LANG_KOREAN is handled. So I add ImeNative.LANG_CHINESE in the if statement.
**Changes:**
- CefSharp.Wpf.Experimental.WpfImeKeyboardHandler.cs is modified.
from
` if (languageCodeId == ImeNative.LANG_KOREAN)
{...}`
to
` if (languageCodeId == ImeNative.LANG_KOREAN || languageCodeId == ImeNative.LANG_CHINESE)
{...}`
- I have tested Chinese IME on windows 10, version 2004, and it works well.
**Checklist:**
=> WPF - Fix Chinese IME character Composition issue

CefSharp.Core/Internals/ClientAdapter.cpp, CefSharp.Core/Internals/ClientAdapter.h, CefSharp.Example/CefSharp.Example.csproj, CefSharp.Example/Handlers/AudioHandler.cs, CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.WinForms.Example/BrowserTabUserControl.cs, CefSharp.WinForms/ChromiumWebBrowser.cs, CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/CefSharp.csproj, CefSharp/Enums/ChannelLayout.cs, CefSharp/Handler/IAudioHandler.cs, CefSharp/IWebBrowser.cs, CefSharp/Internals/InternalWebBrowserExtensions.cs, CefSharp/Structs/AudioParamaters.cs
Resolves #3152
**Summary:** 
Re-Add `AudioHandler` implementation which was removed (was removed `upstream`).
- Add `IAudioHandler` interface
- Add `browser.AudioHandler` property 
This has had minimal testing, the basic wrapper appears to be working correctly, modifying `AudioParameters` is reflected as expected.
**Checklist:**
=> Core - Re-Add IAudioHandler

CefSharp.Wpf/DelegateCommand.cs
**Summary:** `new EventArgs` can be replaced with `EventArgs.Empty` to avoid an object allocation.
**Changes:**
- replaced `new EventArgs()` with `EventArgs.Empty`
**Checklist:**
=> Use EventArgs.Empty in DelegateCommand

CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.netcore.vcxproj, CefSharp.Core/CefSharp.Core.netcore.vcxproj
**Summary:** https://github.com/cefsharp/CefSharp/commit/3e5133dbb3601142ee9f0ec81854c614a6dc7462 got committed before https://github.com/cefsharp/CefSharp/pull/3181 so these projects weren't upgraded
**Changes:** Upgrade to CEF 84.3.3 in netcore projects
Build locally. Before they failed with: 
```
2>P:\CefSharp\CefSharp.BrowserSubprocess.Core\Stdafx.h(15,10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "include/cef_base.h": No such file or directory
```
**Checklist:**
=> Upgrade to CEF 84.3.3 in netcore projects

appveyor.yml
**Part of**: #3197
**Summary:**
- run netcore tests on appveyor
- build x86 and x64 so `CefSharp.Common.NETCore` gets packaged
**Changes:**
- adjusted appveyor.yml to run netcore tests and build x86/x64 so all nuget packages can be generated
https://ci.appveyor.com/project/campersau/cefsharp/builds/34657294
**Checklist:**
=> Net Core - AppVeyor run tests and build x86/x64

build.netcore.ps1
**Part of:** #3197
**Summary:**
- Use msbuild directly for restore. When using `dotnet msbuild` the tests somehow get stuck.
Before the switch to `build.netcore.ps1` msbuild was also used directly: https://github.com/cefsharp/CefSharp/commit/74012ffe0ce04d092d33a8e42fc818825b2c8905#diff-180360612c6b8c4ed830919bbb4dd459L32
**Changes:**
- Use msbuild directly for restore in `build.netcore.ps1`
https://ci.appveyor.com/project/campersau/cefsharp/builds/34716073/job/51gt2da87f0uqi1g
**Checklist:**
=> Net Core - Use msbuild directly for restore

CefSharp.Core/Cef.h
**Summary:**
- I have fixed typos in `Cef.Initialize` method documentation
**Checklist:**
=> Fix typos in Cef documentation

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj, CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj.filters, CefSharp.BrowserSubprocess.Core/JavascriptPromiseHandler.h, CefSharp.BrowserSubprocess.Core/Wrapper/Frame.cpp, CefSharp.BrowserSubprocess.Core/Wrapper/Frame.h, CefSharp.Core/Internals/CefFrameWrapper.cpp, CefSharp.Core/Internals/CefFrameWrapper.h, CefSharp.Test/OffScreen/OffScreenBrowserBasicFacts.cs, CefSharp/IFrame.cs, CefSharp/WebBrowserExtensions.cs
**Summary:**
Use newly added `EvaluateScriptAsPromiseAsync` extension method (add `using CefSharp;`) to evaluate javascript that 
returns a promise. Uses `Promise.resolve` to return the script execution into a promise regardless, `EvaluateScriptAsPromiseAsync("return 53")` will be turned into a promise.
Differs from other `EvaluateScriptAsync` methods in that you **must** return a result.
```js
//This will return 42
await browser.EvaluateScriptAsPromiseAsync("return 42");
//This will return undefined
await browser.EvaluateScriptAsPromiseAsync("42");
```
**Changes:**
- Add useImmediatelyInvokedFuncExpression param to EvaluateScriptAsync which wraps the script in an IIFE
with the cefSharpInternalCallbackId variable defined in scope to allow for deferred completion
- Wrap script in …
=> Enhancement - Add EvaluateScriptAsPromiseAsync

CefSharp.Core.RefAssembly/CefSharp.Core.cs, CefSharp.Core/Cef.h, CefSharp.Core/CefSharp.Core.netcore.vcxproj, CefSharp.Core/CefSharp.Core.netcore.vcxproj.filters, CefSharp.Core/CefSharp.Core.vcxproj, CefSharp.Core/CefSharp.Core.vcxproj.filters, CefSharp.Core/RequestContext.h, CefSharp.Core/RequestContextBuilder.cpp, CefSharp.Core/RequestContextBuilder.h, CefSharp.Example/Handlers/RequestContextHandler.cs, CefSharp.Test/CefSharp.Test.csproj, CefSharp.Test/CefSharp.Test.netcore.csproj, CefSharp.Test/CefSharpFixture.cs, CefSharp.Test/Framework/RequestContextBuilderFacts.cs, CefSharp.Test/Framework/RequestContextExtensionFacts.cs, CefSharp.Test/OffScreen/OffScreenBrowserBasicFacts.cs, CefSharp.Test/SkipIfRunOnAppVeyorFact.cs, CefSharp.Test/app.config, CefSharp.Test/packages.config, CefSharp/CefSharp.csproj, CefSharp/Handler/RequestContextHandler.cs, CefSharp/Internals/CefThread.cs, CefSharp/Preferences/SetPreferenceResponse.cs, CefSharp/RequestContextExtensions.cs
**Fixes:** 
Issue #3235 
**Summary:**
Simplifies the setting of proxy preference
**Changes:** 
- Add new `RequestContextHandler` default implementation
- Add new extension methods
- Add Fluent API for setting the proxy server
Example of new API looks like this:
```c#
var requestContext = RequestContext
.Configure()
.WithProxyServer("127.0.0.1", 8080)
.Create();
using (var browser = new ChromiumWebBrowser("http://cefsharp.github.io/", requestContext: requestContext))
{
await browser.LoadPageAsync();
var mainFrame = browser.GetMainFrame();
Assert.True(mainFrame.IsValid);
Assert.Contains("cefsharp.github.io", mainFrame.Url);
output.WriteLine("Url {0}", mainFrame.Url);
}
```
Basic Unit test (only runs locally) spawns a proxy server and makes a simple page load …
=> Enhancement - Simplify Setting of RequestContext Proxy

NuGet/PackageReference/CefSharp.Common.NETCore.targets
**Issue:** cefsharp/CefSharp#3197
**Summary:**
- Adjust the `RuntimeIdentifier` check in `CefSharp.Common.NETCore.targets` to make it work with non-portable RIDs like `win7-x64` or `win10-x86`.
**Changes:** 
- Changed the comparison of the `RuntimeIdentifier` to not check for exact RIDs like `win-x64`, but check that the string starts with `win` and that it contains the architecture like `-x64`.
- Note: I used `.Contains('-x64')` rather than `.EndsWith('-x64')` as there seem to be some RIDs that have [another suffix](https://github.com/dotnet/runtime/blob/f8e9156244606582c202c9f01be571baf523cccf/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json#L2974), like `win7-x64-aot`, which is described as `[additional qualifiers]` in [.NET Core RID …
=> .NET Core - Allow non-portable RuntimeIdentifiers

CefSharp.Test/OffScreen/OffScreenBrowserBasicFacts.cs, CefSharp/WebBrowserExtensions.cs
**Fixes:** Stack Overflow issue https://stackoverflow.com/questions/65229445/evaulatescriptaspromiseasync-and-async-await
**Summary:**
- Added `async` to the `GetPromiseHandlerScript` `innerImmediatelyInvokedFuncExpression` function. This allows for `await` to be used in methods passed to this. 
- Modified `GetPromiseHandlerScript` to use an async function
- Added tests for async/await usage to `OffscreenBrowserBasicFacts`. Tests pass. 
- Added tests Unit tests to `OffscreenBrowserBasicFacts.cs`, specifically returning values, as well as using `fetch` to make an AJAX request. 
**Checklist:**
=> Add async to EvaluateScriptAsPromiseAsync and tests

CefSharp.Example/Properties/Resources.Designer.cs, CefSharp.Example/Resources/BindingTest.html, CefSharp.Example/Resources/BindingTestAsync.js, CefSharp.Example/Resources/BindingTestNetCore.html, CefSharp.Example/Resources/BindingTestSingle.html, CefSharp.Example/Resources/BindingTestsAsyncTask.html, CefSharp.Example/Resources/LegacyBindingTest.html, CefSharp.Example/Resources/PostMessageTest.html
**Summary:** Simplify BindObjectAsync unit tests.
**Changes:**
- Use native async-await where possible, as well as built-in QUnit methods as appropiate.
=> Example - Simplify BindObjectAsync tests with QUnit

CefSharp.Wpf/Experimental/WpfIMEKeyboardHandler.cs
**Fixes:** #3004
**Summary:** 
- Fix chinese IMEs ( such as "sogou pinyin", "qq pinyin" etc. ) input window position.
**Changes:** 
- I have added a piece of code to WpfImeKeyboardHandler.cs to cast "ImmSetCompositionWindow" to set the chinese IME position. 
- I have tested some chinese common IMEs ( such as "sogou pinyin", "qq pinyin" ,"Microsoft Pinyin IME" ) on Windows 10 and Windows 7, and it looks workable.
**Checklist:**
=> WPF - Fix chinese IMEs ( such as "sogou pinyin", "qq pinyin" etc. ) input window position.

CefSharp.Wpf/Experimental/WpfIMEKeyboardHandler.cs
This is a fix in response to the issue of not emitting spaces in Japanese IME (from @karthikeyancdm).
After all, it turns out that ImeSetComposition() and ImeFinishComposingText() should be invoked inside OnImeComposition() regardless of the current state of the IME language.
**Issue: #1262
**Summary:** 
- Fixed an error that a user cannot type spaces during Japanese IME is on 
**Changes:** 
- Removed the if (lang == KOREAN || lang == CHINESE) statement in OnImeComposition() so that it effectively makes it equivalent to if (lang == KOREAN || lang == CHINESE || lang == JAPANESE). (e.g. executing it if the language is Japanese as well)
Tested with Japanese IME installed on Windows 10 (20H2). …
=> WPF - Japanese IME unable to enter space

CefSharp.Test/CefSharp.Test.csproj, CefSharp.Test/JavascriptBinding/JavaScriptObjectRepositoryFacts.cs, CefSharp/Internals/JavascriptObjectRepository.cs
**Fixes:** 
**Summary:** Sometimes, the registered Javascript object does not have a namespace, at this time this function will throw a ```NullReferenceException```.
**Changes:** 
- Add null reference check for IsComplexType function 
This problem is obvious and does not need to be tested 
**Checklist:**
=> Javascript Binding - Allow binding to classes in the global namespace

CefSharp/CefSharpSettings.cs
**Summary:**
I have updated the documentation of the `CefSharpSettings.WcfEnabled` method according to https://github.com/cefsharp/CefSharp/issues/2990 which replaces `browser.RegisterAsyncJsObject` and `browser.RegisterJsObject` methods with `JavascriptObjectRepository.Register(isAsync: true/false)`.
**Changes:**
- Updated the CefSharpSettings.WcfEnabled summary
**Checklist:**
=> Update the CefSharpSettings.WcfEnabled summary

CefSharp.Core.Runtime.RefAssembly/CefSharp.Core.Runtime.netcore.cs
**Summary:**
- I build the netcore projects and this property got added automatically. Looks like it was missed in https://github.com/cefsharp/CefSharp/commit/94fb45766de8e0b809bc9ef9195c4e0a9259919f
=> Add ChromeRuntime property to RefAssembly CefSharp.Core.Runtime.netcore

CefSharp/Enums/TransitionType.cs
which was added in https://github.com/chromiumembedded/cef/commit/a141082b91c06979bbed2a6aba60708328400b33
Set breakpoint in `ExampleResourceRequestHandler.OnBeforeResourceLoad` and observe `request.TransitionType`. See screenshots.
Before:
After:
**Checklist:**
=> Core - Add TransitionType.DirectLoad enum value

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.h, CefSharp.Core.Runtime/ManagedCefBrowserAdapter.cpp, CefSharp.Test/CefSharpFixture.cs, CefSharp.Test/JavascriptBinding/IntegrationTestFacts.cs, CefSharp/JavascriptBinding/JavascriptBindingSettings.cs
**Summary:**
The Javascript methods that CefSharp provides in relation to JavaScript Binding are
created using a Global (window) Object. Settings this property allows you to disable
the creation of this object. Features like EvaluateScriptAsPromiseAsync that rely on
the creation of this object will no longer function.
**Changes:** 
- Add JavascriptBindingSettings.JavascriptBindingApiEnabled property
- Added test cases
- Unit Tests included
**Checklist:**
=> JavascriptBinding - Add JavascriptBindingSettings.JavascriptBindingApiEnabled property

CefSharp.Core.Runtime/Internals/CefBrowserHostWrapper.cpp
The handling of AltGr characters in CefBrowsterHostWrapper did not cover capital diacritic letters. This commit adds handling for the Shift + AltGr + modifier combination.
**Fixes: #3626**
**Summary:**
- I have added support for Shift+AltGr character input in CefSharp WPF
**Changes:** 
- I have modified the current handling of AltGr characters in the CefBrowsterHostWrapper class by extending support to Shift+Ctrl+Alt combination
- ran CefSharp.WPF.Example
- navigate to www.google.com
- enter capital polish letters (Shift + AltGr + EOASLZXCN) 
- enter small polish letters (AltGr + eoaslzxcn), 
- enter special characters (Shift + 1-9)
**Checklist:**
=> WPF - Add support for Shift+AltGr

CefSharp.Wpf/Experimental/WpfIMEKeyboardHandler.cs
**Fixes:**
`GetBrowserHost` will throw exception when browser is not initalized.
**Summary:**
Check `IsBrowserInitialized` before `GetBrowserHost`
**Changes:**
Check `IsBrowserInitialized` before `GetBrowserHost`
**How Has This Been Tested?** 
Set `ChromiumWebBrowser.WpfKeyboardHandler` to `WpfIMEKeyboardHandler` and test with CefSharp.Wpf.Example.
**Checklist:**
=> WPF - Fix WpfIMEKeyboardHandler crash when browser is not initalized.

CefSharp.Example/CefSharp.Example.csproj, CefSharp.Example/CefSharp.Example.netcore.csproj, CefSharp.Example/Handlers/AudioHandler.cs, CefSharp.WinForms.Example/BrowserTabUserControl.cs, CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs
**Fixes:** #2806
**Summary:** I have updated example for Audio Handler
**Changes:**
- Overrided GetAudioParameters method. return true to activate audio stream capture
- Overrided OnAudioStreamPacket method. Data from data pointer converted to PCM, 32-bit, float and written to file.
I tested AudioHandler example class in my application. Application has Offscreen type.
In my application used Nuget packet CefSharp.OffScreen, v91.1.211
PC: Windows 10, AMD Ryzen 7, 3700X, NVidia GT1030, RAM 32GB
Visual Studio 2019 Community
**Checklist:**
=> Updated example for Audio Handler

CefSharp.Wpf/Experimental/Accessibility/AccessibilityHandler.cs, CefSharp.Wpf/Experimental/Accessibility/AccessibilityNode.cs, CefSharp.Wpf/Experimental/Accessibility/AccessibilityTree.cs
**Fixes:** #3766
**Summary:**
- Added `ContainsKey` check for `ax_tree_id` to avoid `KeyNotFoundException`.
- Convert class member `attributes` to a local variable to avoid `SEHException` when browser gets closed.
<details>
<summary>SEHException (in german)</summary>
```
System.Runtime.InteropServices.SEHException
HResult=0x80004005
Nachricht = Eine externe Komponente hat eine Ausnahme ausgelöst.
Quelle = <Die Ausnahmequelle kann nicht ausgewertet werden.>
Stapelüberwachung:
<Die Ausnahmestapelüberwachung kann nicht ausgewertet werden.>
Diese Ausnahme wurde ursprünglich von dieser Aufrufliste ausgelöst:
CefSharp::Internals::MCefRefPtr<CefValue>::!MCefRefPtr<CefValue>(void) in MCefRefPtr.h
[Externer Code]
```
</details>
Manually with WPF example. …
=> WPF - Accessibility check for "ax_tree_id" key and avoid referencing IValue in class member

CefSharp.Core.Runtime/Internals/CefBrowserHostWrapper.cpp
**Fixes:** 
**Summary:**
- Support ALT(Left) and ALT GR (Right) Key.
- This allows: CTRL+ ALT +[SPECIFIC KEY] to input symbols with WPF (e.g. German keyboard layout)
**Changes:**
- Extended a if condition ([here](https://github.com/cefsharp/CefSharp/blob/b9de94303eb87141fbad7e28ad1399ea2d73ac67/CefSharp.Core.Runtime/Internals/CefBrowserHostWrapper.cpp#L382)) to proof whether the ALT key is pressed and not only ALT GR.
- Tested with a vanilla project and also with the Cef example browser, which is inside the master src.
- Entered symbols ² ³ { [ ] } } \ @ on certain search engines within Cef example browser
(Layout: German)
**Checklist:**
=> WPF - Support ALT(Left) and ALT GR (Right) Key.

CefSharp.Core.Runtime/Internals/CefBrowserHostWrapper.cpp, CefSharp.Core.Runtime/Internals/CefBrowserHostWrapper.h, CefSharp/DevTools/DevToolsClient.cs, CefSharp/IBrowserHost.cs
**Fixes:** #3341
**Summary:**
- Added `GetNextDevToolsMessageId` to `IBrowserHost` to get browser scoped message ids for executing dev tools methods.
**Changes:**
- Added `IBrowserHost.GetNextDevToolsMessageId` and using it inside of `DevToolsClient`.
Unittests
**Checklist:**
=> DevTools - Add GetNextDevToolsMessageId to IBrowserHost

CefSharp.Core.Runtime/Cef.h, CefSharp.Core/Cef.cs
Add property Cef.IsShutdown to allow checks for the shutdown state of Cef runtime (#3782)
… Cef runtime (#3782)
**Fixes:** #3782
**Summary:** Cef object will exponse the private `_hasShutdown` field as `IsShutdown` property.
Manual test of the code.
**Checklist:**
=> Add property Cef.IsShutdown #3782

CefSharp.BrowserSubprocess.Core/Serialization/V8Serialization.cpp, CefSharp.Test/JavascriptBinding/IntegrationTestFacts.cs
**Fixes:**
Resolves #3808
- Array serialization now correctly handles empty elements within the source array
-No structural changes - use HasValue to check if an element is empty
Used WinForms example with several inputs to try and break it but - it works.
**Checklist:**
=> Fix for arrays with empty elements

CefSharp/Enums/CefErrorCode.cs
**Related:** #3817 
**Summary:**
- Updated CefErrorCode using https://raw.githubusercontent.com/chromium/chromium/94.0.4606.50/net/base/net_error_list.h and steps described in https://github.com/cefsharp/CefSharp/pull/3785
**Changes:**
- See https://github.com/cefsharp/CefSharp/pull/3785
The [new error code `DNS_NAME_HTTPS_ONLY`](https://github.com/chromium/chromium/commit/ac9aafb6a3a81537bba6286f65aa84b885f062bd) is missing the minus sign which [got fixed in version `95`](https://github.com/chromium/chromium/commit/651bd32d5d559010ed5dd44aee0f33c7a0162301). 
Build works.
**Checklist:**
=> Core - Update CefErrorCode

CefSharp.Wpf.Example/Handlers/MenuHandler.cs, CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs, CefSharp.Wpf/Handler/ContextMenuExecuteModel.cs, CefSharp.Wpf/Handler/ContextMenuHandler.cs
**Summary:**
Implements a native `WPF` context menu
Based of https://github.com/chromiumembedded/cef/blob/ba46b8c53ed0f46cec82a1aebaec173784deb6e4/libcef/browser/menu_manager.cc#L385
**Changes:**
- Adds `WPF` specific IContextMenuHandler implementation that creates a native System.Windows.Controls.ContextMenu
Manual testing so far
**Checklist:**
=> WPF - Add System.Windows.Controls.ContextMenu based ContextMenuHandler

CefSharp.Core/CefSharp.Core.csproj, CefSharp/CefSharp.csproj
**Summary:**
- Ignore netcore output in netframework projects
**Changes:**
- In https://github.com/cefsharp/CefSharp/commit/65534275b75ef41814770cc1947ba6f0e97b6995 these changes were missing. For WinForms / WPF / OffScreen they are already ignored: https://github.com/cefsharp/CefSharp/commit/e4e0f22ca7b574fb4a62d121c90c150c2a691876
Build works.
**Checklist:**
=> Core - Ignore netcore output in netframework projects

CefSharp.Core.Runtime.RefAssembly/CefSharp.Core.Runtime.netcore.cs
**Summary:**
- Add `Cef.ParseUrl` to RefAssembly
**Changes:**
- It got added automatically when building the netcore version.
- The method was originally added in https://github.com/cefsharp/CefSharp/commit/c5ba1ce43053575faac6a938042e77c12d1a9f97
Build works.
**Checklist:**
=> Core - Add Cef.ParseUrl to RefAssembly

README.md
according to https://bitbucket.org/chromiumembedded/cef/wiki/BranchesAndBuilding the 95 release branch is 4638, instead of the stated 4606 of the 94 release
**Checklist:**
=> README.md: correct CEF Version to 4638 for CefSharp 95

CefSharp.Wpf/Experimental/WpfIMEKeyboardHandler.cs
**Fixes:** #3911  
**Summary:** 
[Fixed] Text cursor displayed at the left side of currrently writing character when typing Korean 
**Changes:**
[Changed] selectionRange of ImeSetComposition for Korean
Manually using the Microsoft Korean IME keyboard.
**Checklist:**
=> WPF - Korean IME fix cursor displayed at the left side of current character

CefSharp.Test/Javascript/EvaluateScriptAsyncFacts.cs
**Summary:** Fixes CanEvaluateDoubleValues test by not relying on the current culture
These tests fail with e.g. german locale.
Running unittest with german locale.
**Checklist:**
=> Test - Fix CanEvaluateDoubleValues by not relying on the current culture

CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.Test/OffScreen/OffScreenBrowserBasicFacts.cs
**Fixes:** https://github.com/cefsharp/CefSharp/discussions/3959#discussioncomment-1947117
**Summary:** The `AfterPaint` event receives the scaled `Width` and `Height`, so the check for that must account for that.
That's what I meant with this comment:
>  (Scale does not work as the check for width / height needs to use the scaled sizes: * deviceScaleFactor)
**Changes:**
- Fix ResizeAsync with deviceScalingFactor
- Added new Test cases
Unittest
**Checklist:**
=> OffScreen - Fix ResizeAsync with deviceScalingFactor

CefSharp.Example/AcceptRangeResourceHandler.cs, CefSharp/ResourceHandler.cs
**Summary:**
Added disposal of unused callback to `ResourceHandler.Skip()` like it is in `Read()`.
**Changes:**
A trivial modification to `ResourceHandler` and `AcceptRangeResourceHandler`.
**How Has This Been Tested?**
As per our Gitter conversation, it has not been tested.
**Checklist:**
=> Fix not disposing callback in ResourceHandler.Skip

CefSharp/IResourceRequestHandlerFactory.cs
I have just discovered that when `HasHandlers` returns `false`, the `GetResourceRequestHandler` method is never executed.  Presumably this is an optimisation which happens inside of CEF, as I can see that the `HasHandlers` property value goes all way back to the C++ native project.
I was about to suggest removing this optimisation because it'd be trivial to optimise and return early inside the default factory impl in C# world.  If it goes all the way down to CEF then that's less easy and so the next best thing would be to document it.
**Fixes:** _Has no related issue_
**Summary:** Addition to docs (more info above)
**Changes:** `IResourceRequestHandlerFactory` (comments only)
**How Has This Been Tested?**  It has not, no functional changes made
**Checklist:**
=> Update docs for IResourceRequestHandlerFactory

CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.Test/Framework/HasHandlerFacts.cs, CefSharp.Test/OffScreen/WaitForRenderIdleTests.cs, CefSharp.Test/WebBrowserTestExtensions.cs, CefSharp.Test/Wpf/WaitForRenderIdleTests.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp/Internals/TaskTimeoutExtensions.cs
**Summary:** 
- WPF/OffScreen - Add WaitForRenderIdleAsync method
- Only for .Net 4.6.2 and above
**Changes:**
- Task resolves when render has been idle for the specified time
- Make TaskTimeoutExtensions public (they're not extension methods as this was expected)
xUnit Tests
**Checklist:**
=> WPF/OffScreen - Add WaitForRenderIdleAsync

CefSharp/SchemeHandler/FolderSchemeHandlerFactory.cs
**Fixes:**
- #2535 (better than this)
- Fix `FolderSchemeHandlerFactory` keeping files locked for the process lifetime
If a page or other resource is loaded via a scheme that uses `FolderSchemeHandlerFactory`, subsequently attempting to delete or overwrite the corresponding file results in a "file in use" exception -- even if the browser has navigated elsewhere or disposed beforehand.
This appears to be because `ResourceHandler.FromStream` will by default not close streams even though (in this case) they are only used for a single request.  So we ought to tell it to do so.  (It would be safer if `FromStream` did dispose by default, but that would be a breaking change.)
**How …
=> Fix FolderSchemeHandlerFactory locking files

CefSharp.BrowserSubprocess/CefSharp.BrowserSubprocess.csproj, CefSharp.BrowserSubprocess/CefSharp.BrowserSubprocess.netcore.csproj
**Fixes:**
https://github.com/cefsharp/CefSharp/discussions/4231
Follow-Up to #3986 
**Summary:**
- Use decimal instead of hexadecimal notation for the `editbin /STACK:` command, to work-around a regression introduced in editbin v14.33 (and possibly 14.32 or 14.31) that no longer recognizes the `0x...` hex format.
**Changes:** 
- I modified the `editbin` command line in `CefSharp.BrowserSubprocess.csproj` and `CefSharp.BrowserSubprocess.netcore.csproj` to specify `/STACK:8388608` instead of `/STACK:0x800000` for the `editbin` command, which works with editbin v14.33.
- Built the projects using Visual Studio 2022 Version 17.3.3, and verified with `dumpbin /headers` that before the change, for `CefSharp.BrowserSubprocess.exe` it showed `0 size of stack …
=> Use decimal instead of hexadecimal notation for "editbin" command

CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp.Wpf/Internals/WpfExtensions.cs
**Fixes:** #4286
**Summary:** 
Enable forwarding keyboard modifiers to drag events in WPF CefSharp
- Added a new extension method next to the others in `WpfExtensions` to get a `CefEventFlags` value for the keyboard modifiers of drag events.
- Used said method in the `GetMouseEvent(DragEvent)` function of `ChromiumWebBrowser`.
- Tested by opening the fiddle from the issue (https://jsfiddle.net/_Yhn/24jmqgbh/) within the CefSharp.Wpf.Example and verifying the output of the events (Using Win10 in a VM)
**Checklist:**
=> WPF - Send keyboard modifiers with drag events

CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.h, CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj, CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj.filters, CefSharp.BrowserSubprocess.Core/JavascriptPromiseResolverCatch.h, CefSharp.BrowserSubprocess.Core/JavascriptPromiseResolverThen.h, CefSharp.Example/CefExample.cs, CefSharp.Test/Javascript/EvaluateScriptAsyncFacts.cs, CefSharp.Test/Javascript/JavascriptCallbackFacts.cs
**Fixes:** #4276
**Summary:** 
Can now directly return a Promise when evaluating javascript
**Changes:** 
- EvaluateScriptAsync and IJavascriptCallback.ExecuteAsync now check if the returned object is a promise
and subscribe to the then/catch methods to send the deferred response back to the browser.
- Leaves the existing Evaluate As promise method unchanged.
New unit tests added
**Checklist:**
=> Enhancement - Improve Promise support

CefSharp.props
**Issue:**
There's no open issue, because I lost the logs and reproducing it would be quite time consuming. 
When build with Visual Studio Build Tools 2022 there's an error Message complating that the library libcef_dll_wrapper.lib was not found and the library path is similar to "[...]\**VSVS2022**\[...]".
**Summary:**
The msbuild property VisualStudioProductVersion is used to build the property AdditionalLibraryDirectories. For example here:
https://github.com/cefsharp/CefSharp/blob/a69e6ee2a48bfbbe6804608bbab86d2cb3fddd85/CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.netcore.vcxproj#L160
There's already the prefix "VS" in place, in front of $(VisualStudioProductVersion). Thus VisualStudioProductVersion should not contain the "VS" prefix.
Any other occurence of …
=> Fix Visual Studio 2022 support

CefSharp.Core.Runtime/Internals/ClientAdapter.cpp, CefSharp.Core.Runtime/Internals/ClientAdapter.h, CefSharp.WinForms.Example/Handlers/WinFormsLifeSpanHandlerEx.cs
Related discussion https://github.com/cefsharp/CefSharp/discussions/4438
**Summary:** 
- Rewrite HasParent checks to make sure that IWebBrowser.Set* methods are only called for a IBrowser
instance that's directly associated with a ChromiumWebBrowser instance
**Changes:**
- HasParent check has now been replaced with IsHostedBrowser
which has additional check to make sure the internal
IWebBrowser.Set* methods are only called for a IBrowser
instance that's directly associated with a ChromiumWebBrowser instance
This resolves issues with DevTools being opened for a popup hosted
in a ChromiumWebBrowser instance.
Tested using the `LifeSpanHandler` implementation in the comment below.
**Checklist:**
=> Core - ClientAdapter improve HasParent checks

CefSharp.Wpf.Example/App.xaml, CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj, CefSharp.Wpf.Example/CefSharp.Wpf.Example.netcore.csproj, CefSharp.Wpf.Example/MainWindow.xaml, CefSharp.Wpf.Example/Views/BrowserTabView.xaml
Some very minor UI improvements to the WPF Example using https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit
There are further improvements that could be made, the custom TabControl needs restyling, tweaks to button colours, handle light/dark mode etc.
=> WPF Example - Implement Material Design

CefSharp.Core/CefSharp.Core.netcore.csproj, CefSharp.OffScreen/CefSharp.OffScreen.netcore.csproj, CefSharp.WinForms/CefSharp.WinForms.netcore.csproj, CefSharp.Wpf/CefSharp.Wpf.netcore.csproj, CefSharp/CefSharp.netcore.csproj
**Fixes:** #4558 
**Summary:** The .NET 6.0 SDK introduced a breaking change meaning that reference assemblies are no longer automatically copied from the intermediate build directory to the output directory. An additional MsBuild property is now required.
**Changes:** Included the ProduceReferenceAssemblyInOutDir in all required netcore projects
Has been tested using build.ps1 script (VS2022) and building in Visual Studio 2022. 
Has not been tested with VS2019 build tools 
**Checklist:**
=> NetCore - Generate Reference Assemblies building with VS2022

CefSharp.Wpf/Rendering/WritableBitmapRenderHandler.cs
Force initial bitmap creation upon wakeup when the image.source is null... Happens if sizing etc. rapidly and the UI thread short circuits when CreateNewBitMap is true and the first wake up occurs with it 'false' amd image.Source is still null...
**Fixes:** [issue-number] 
Fixes: #4612 
- Add a missing null reference check to force bitmap creation in relation to #4612
- I added a missing null check to force Bitmap creation when dispatch to UI thread first wakes up. 
We consume CEFSharp as part of a larger application.. The issue at hand was noticed when using our system's scripting/playback mechanism.  I have locally merged the fix into a …
=> WPF - WritableBitmapRenderHandler Avoid null bitmap references upon wakeup.

CefSharp.Core.Runtime.RefAssembly/CefSharp.Core.Runtime.netcore.cs, CefSharp.Core.Runtime/DragData.h, CefSharp/IDragData.cs
**Summary:**
The CEF side broke up filename and file paths.  For more info see: https://github.com/chromiumembedded/cef/issues/3568
This broke out application which was expecting them to be in the old format.
- CEF changed DragData filenames to only be the the file names and removed path info
- CEF added FilePaths as a separate filed in DragData
- This PR makes that data available 
- FilePaths added to DragData
The test app doesn't expose this anywhere.  So I put a break point in IDragHandler.OnDragEnter in CefSharp\CefSharp.Wpf.Example\Handlers\DragHandler.cs and inspected the data manually.
Our application uses this data and ran through our internal unit tests to verify.
**Checklist:**
=> Add in file paths data to DragData

CefSharp/Internals/TaskExtensions.cs
**Summary:**
- Starting the timer after it is initialized avoids a race condition where the callback could be called before the timer variable was assigned. See also https://stackoverflow.com/a/17263385
Sometimes I saw crashes like this when the timeout was quite small and the CPU usage was high.
```
System.NullReferenceException: Object reference not set to an instance of an object.
at CefSharp.Internals.TaskExtensions.<>c__DisplayClass0_0`1.<WithTimeout>b__0(Object state) in C:\projects\cefsharp\CefSharp\Internals\TaskExtensions.cs:line 23
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.ExecutionContext.RunInternal(ExecutionContext …
```
=> WithTimeout: start timer after initialization

CefSharp.OffScreen/DefaultRenderHandler.cs
**Summary:**
It can happen when a `RenderHandler` is detached from the browser and then disposed that `GetScreenInfo` still gets called because of the local copy [here](https://github.com/cefsharp/CefSharp/blob/ed1763ee9510dca9e54ab766ea7cf305f71d2aa2/CefSharp.OffScreen/ChromiumWebBrowser.cs#L807) which then results in a NRE.
Our simplified code looks something like this:
```c#
var renderHandler = new DefaultRenderHandler(browser);
browser.RenderHandler = renderHandler;
// take screenshot here
browser.RenderHandler = null; // detach renderHandler
renderHandler.Dispose();
// NRE on different / cef thread => crash
```
```
System.NullReferenceException: Object reference not set to an instance of an object.
at CefSharp.OffScreen.DefaultRenderHandler.GetScreenInfo() in …
```
=> OffScreen - Check if browser is not null in GetScreenInfo/GetViewRect

CefSharp.Wpf/Experimental/WpfIMEKeyboardHandler.cs
**Summary:** 
- Fix the WPF browser is embedded in the Winfrom form, the Chinese IMEs window (such as "sogou pinying","qq...") will not follow the cursor when inputting Chinese. This problem does not exist in the WPF form.
**Changes:**
- Modify the WpfImeKeyboardHandler class and add a custom function GetOutermostElement to obtain the outermost visual element.
- Modify the ChangeCompositionRange method and add that when the parent window Window.GetWindow(owner) is empty, call the function GetOutermostElement to obtain the outermost visual element as the input method window position calculation container.
**The wrong position**
**The correct position**
After the fix, the input method window correctly follows the cursor …
=>  WPF - Fix the Chinese IMEs (such as "sogou pinyin", "qq...") window position is incorrect in Winform form embedded wpf control.

build.ps1
By default vswhere returns a non-zero error code making our error handling fail
I don't remember if I am mis-remembering a line suppress error option in powershell but I couldn't find it, and I didn't want to try/catch this.
=> fix: actually support vswhere not finding something

CefSharp.BrowserSubprocess.Core/BindObjectAsyncHandler.h, CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp, CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.h, CefSharp.BrowserSubprocess.Core/CefBrowserWrapper.h, CefSharp.BrowserSubprocess.Core/JavascriptCallbackRegistry.cpp, CefSharp.BrowserSubprocess.Core/Wrapper/Browser.cpp, CefSharp.BrowserSubprocess.Core/Wrapper/Browser.h, CefSharp.BrowserSubprocess.Core/Wrapper/Frame.cpp, CefSharp.BrowserSubprocess.Core/Wrapper/Frame.h, CefSharp.Core.Runtime/Internals/CefBrowserWrapper.cpp, CefSharp.Core.Runtime/Internals/CefBrowserWrapper.h, CefSharp.Core.Runtime/Internals/CefFrameWrapper.cpp, CefSharp.Core.Runtime/Internals/CefFrameWrapper.h, CefSharp.Core.Runtime/Internals/ClientAdapter.cpp, CefSharp.Core.Runtime/Internals/JavascriptCallbackProxy.cpp, CefSharp.Core.Runtime/Internals/JavascriptCallbackProxy.h, CefSharp.Core.Runtime/Internals/Serialization/Primitives.cpp, CefSharp.Test/CefSharp.Test.csproj, CefSharp.Test/CefSharp.Test.netcore.csproj, CefSharp.Test/Framework/ConcurrentMethodRunnerQueueTest.cs, CefSharp.Test/Framework/JavascritpCallbackConversionTests.cs, CefSharp.Test/Framework/MethodRunnerQueueTests.cs, CefSharp/Handler/FrameHandler.cs, CefSharp/IBrowser.cs, CefSharp/IFrame.cs, CefSharp/Internals/IWebBrowserInternal.cs, CefSharp/Internals/JavascriptCallback.cs, CefSharp/Internals/MethodInvocation.cs, CefSharp/Internals/MethodInvocationResult.cs, CefSharp/Internals/Partial/ChromiumWebBrowser.Partial.cs
**Fixes:** #4737
**Summary:** 
Migrate from Int64 to String for frame identifier
**Changes:** 
-       
- New tests added for `JavascriptCallback` conversion
- Existing tests are passing.
**Checklist:**
=> Change Frame identifier from Int64 to String

build.ps1
**Summary:**
After https://github.com/cefsharp/CefSharp/pull/4763 was merged I have seen in https://ci.appveyor.com/project/cefsharp/cefsharp/builds/49434312/artifacts that the branch name was `HEAD` instead of `master`. Looks like AppVeyor does checkout the commit rather than the branch: https://github.com/appveyor/ci/issues/1606
**Changes:** 
- Added check for `APPVEYOR_REPO_BRANCH` and prefer it over the branch name we get from git.
Manually
**Checklist:**
=> Nuget - Prefer APPVEYOR_REPO_BRANCH

CefSharp.Core.Runtime/Internals/RenderClientAdapter.h, CefSharp/AcceleratedPaintInfo.cs
Implement AcceleratedPaintInfo so the shared texture can be used for accelerated rendering in a custom IRenderHandler.
Code was successfully tested against Direct3D11.1 using SharpDX on Windows 11.
Use SharpDX.Direct3D11.Device1.OpenSharedResource1< Texture2D >(AcceleratedPaintInfo.SharedTextureHandle);
Then copy the contents of this resource to your own Texture2D before returning from OnAcceleratedPaint().
=> Implement AcceleratedPaintInfo

CefSharp.BrowserSubprocess.Core/Serialization/V8Serialization.cpp, CefSharp.Core.Runtime/Internals/Serialization/ObjectsSerialization.cpp, CefSharp.Core.Runtime/Internals/Serialization/Primitives.cpp, CefSharp.Core.Runtime/Internals/Serialization/Primitives.h, CefSharp.Test/Javascript/EvaluateScriptAsyncTests.cs
Related #4358
**Summary:** 
- Adds ability to return an ArrayBuffer copy via EvaluateScriptAsync
- xUnit tests
**Checklist:**
=> Core - Basic ArrayBuffer support for EvaluateScriptAsync

CefSharp.Wpf/ChromiumWebBrowser.cs
**Fixes:** #4801 
**Summary:** 
- This change ensures that only `none`, `move`, `copy`, or `link` can be passed the the browser host to signify a DragEnd event. Specifying multiple flags on the bitmask seems to prevent the event from firing, and therefore the result that is returned from DragDrop.DoDragDrop is compared to the last drag drop effect we have on record.
- When doing further testing after creating the issue, I noticed that the dragEnd event *was* emit when I cancelled the drag drop. Beyond this, when testing and manually specifying the flag, I noticed the event was emit when using the `none`, `move`, `copy`, or `link` flags by themselves in the bitmask, and seemed to correlate with the event's `dataTransfer.dropEvent` field. Given the API specifies that can only be one of …
=> WPF - Ensure only single drag operation is emit on DragSourceEndedAt

CefSharp.Wpf/ChromiumWebBrowser.cs
Extract behaviour into method so user can override if required.
Follow up to PR# 4814
=> WPF - Add GetDragOperationsMask virtual method to allow custom behaviour

CefSharp/Enums/CefErrorCode.cs
**Summary:** Updated CefErrorCode using https://raw.githubusercontent.com/chromium/chromium/126.0.6478.115/net/base/net_error_list.h and steps described in #3785
Build works.
**Checklist:**
=> Core - Update CefErrorCode (126.0.6478.115)

build.ps1
**Fixes:** #4938
Specifying latest gives us the last installed version and is a quick fix without adding more parameters.
Should have 0 effect for where build.ps1 was working and fix where it broke with multiple installs
I ran it ;)
- [  x ] Bug fix (non-breaking change which fixes an issue)
**Checklist:**
- [ x ] Tested the code(if applicable)
- [ x ] The formatting is consistent with the project (project supports .editorconfig)
I think this would happen if you have vs 2022 and preview installed, certainly if you had community and another version installed.
=> fix: take latest vs install if multiple instances exist with vswhere.exe

CefSharp.Test/OffScreen/DownloadHandlerTests.cs
Using `TaskCreationOptions` instead of `TaskContinuationOptions` for `TaskCompletionSource` in test. This was the only place where it was wrong.
=> Test - Use TaskCreationOptions instead of TaskContinuationOptions for TaskCompletionSource

CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.Wpf/ChromiumWebBrowser.cs
**Summary:** 
- When opening popups which close themself (e.g. with `window.close()`) it can happen that the `IBrowser` is already disposed but not the `ChromiumWebBrowser`, which can lead to `ObjectDisposedException` in dispose.
**Changes:**
- Added a check for `IBrowser.IsDisposed` before accessing it.
Manually. Unfortunately I wasn't able to create a test for it yet.
**Checklist:**
=> WPF/OffScreen - Avoid ObjectDisposedException when browser is already disposed

.editorconfig, CefSharp.OffScreen/ChromiumWebBrowser.cs, CefSharp.Wpf/ChromiumWebBrowser.cs, CefSharp.Wpf/IRenderHandler.cs, CefSharp.Wpf/Rendering/AbstractRenderHandler.cs, CefSharp.Wpf/Rendering/AllocHGlobalWritableBitmapRenderHandler.cs, CefSharp.Wpf/Rendering/DirectWritableBitmapRenderHandler.cs, CefSharp.Wpf/Rendering/Experimental/ByteArrayWritableBitmapRenderHandler.cs, CefSharp.Wpf/Rendering/Experimental/CompositionTargetRenderHandler.cs, CefSharp/IWindowInfo.cs
**Fixes:**
See https://github.com/cefsharp/CefSharp/pull/4942#issuecomment-2380104532
**Summary:**
- Enable CA2247 rule in editorconfig and set it to `error` on build
**Changes:**
- Enable CA2247
- Fix some XML doc comments
Manual build.
**Checklist:**
=> editorconfig - Enable CA2247 to error on build

CefSharp.Core.Runtime/Internals/Serialization/V8Serialization.cpp
**Fixes:** #4958
**Summary:**
This adds ExpandoObject support to the SerializeV8SimpleObject path.   We could add support for testing if it is assignable to a idictionary<string,object> which might allow a few more things to work but im not aware off hand what they would be.  Maybe we could add support for any templated IDictionary but that is beyond my CLR c++ knowledge. 
We could eliminate some code potentially merging this and the dictionary function into one.  If the item is an expandoObject we could use the IDictionary constructor of Dictionary to create a Dictionary<string,object> and then use the rest of the IDictionary support that is there.   Let me know if you want me to revise it to that.
**Changes:**
Added specific case for ExpandoObject so should have minimal impact
**How Has …
=> SerializeV8SimpleObject support for ExpandoObjects

CefSharp/Internals/Partial/ChromiumWebBrowser.Partial.cs
**Fixes:** https://github.com/cefsharp/CefSharp/issues/5002
**Summary:**
- Added try catch to avoid `ObjectDisposedException` in `InitialLoad`
**Changes:**
- Added try catch to avoid `ObjectDisposedException` in `InitialLoad`
Not tested.
**Checklist:**
=> Avoid ObjectDisposedException when host got disposed in InitialLoad

CefSharp.Core.Runtime/Internals/ClientAdapter.cpp, CefSharp.Core.Runtime/ManagedCefBrowserAdapter.cpp, CefSharp.Test/JavascriptBinding/JavaScriptObjectRepositoryTests.cs, CefSharp.Test/JavascriptBinding/JavascriptBindingTests.cs, CefSharp/Event/JavascriptBindingEventArgs.cs, CefSharp/Internals/IJavascriptObjectRepositoryInternal.cs, CefSharp/Internals/JavascriptObjectRepository.cs
Issue #5001
**Summary:** 
- Add additional info to event args
**Changes:** 
- Add url to event args
Tests have been updated
**Checklist:**
=> Add Url to JavascriptBindingEventArgs

CefSharp/SchemeHandler/FolderSchemeHandlerFactory.cs
Related to pull request https://github.com/cefsharp/CefSharp/pull/2364
**Summary:**
The original fix can potentially lead to non-existing root path. This PR fixes the issue when the `rootFolder` has "escaped" URL characters even thought that's how the folder is named (e.g. `hello%2Fworld` folder would try to lookup `hello/world` folder which doesn't exist).
**Changes:**
- Moved `WebUtility.UrlDecode` from the full path to absolute path only.
1. I've used CefSharp.Wpf.Example.netcore project, where I've added new custom scheme with `FolderSchemeHandlerFactory`, with the following parameters:
- rootFolder: `"escaped%2Fslash"`
- schemeName: `"app"`
- hostName: `"test"`
2. Then I've created folder `escaped%2Fslash` in the output directory and created two simple …
=> FolderSchemeHandlerFactory Handle URL encoded paths only in absolute path

CefSharp/PostDataExtensions.cs
- We noticed that we had to check the IPostDataElement.Bytes array for null ourselves before calling .GetBody(). This felt a bit weird, so I think it makes sense to handle this in CefSharp code like I did here.
- Added null check for Bytes of IPostDataElement object
By calling .GetBody() on a IPostDataElement object with PostDataType.Empty and Bytes = null.
**Checklist:**
=> Handle case where IPostDataElement.Bytes is null
