cefsharp/CefSharp

- Build.bat
- CefSharp.Core/Internals/CefDragDataWrapper.h
- CefSharp.Core/ManagedCefBrowserAdapter.h
- CefSharp.Wpf.Example/Views/BrowserTabView.xaml
- CefSharp.Wpf/ChromiumWebBrowser.cs
- CefSharp/CefDragOperationsMask.cs
- CefSharp/CefSharp.csproj
- CefSharp/IMouseEvent.cs
- CefSharp/MouseEvent.cs
Hey @amaitland,
I had to re-create, as I could not change the branch.
I'll just compare with `master` in going forward.
> Added Drag Drop support to allow dragging objects into the browser (PR to master)

- CefSharp.Core/BrowserSettings.h
- CefSharp.Core/ManagedCefBrowserAdapter.h
- CefSharp.OffScreen.Example/Program.cs
- CefSharp.OffScreen/ChromiumWebBrowser.cs
- CefSharp.WinForms.Example/BrowserTabUserControl.cs
- CefSharp.WinForms/ChromiumWebBrowser.cs
- CefSharp.Wpf/ChromiumWebBrowser.cs
See #785 for details, but this fixes the obvious issue in #785 as well as some other problematic looking IDisposable patterns in the other ChromiumWebBrowser flavors.
> Cleanup/Implement Dispose Pattern

- README.md
@jornh, I noted the link was wrong. Feel free to merge.
> Fixed incorrect link

- README.md
Add MyGet reference to Readme.md for those looking for CI `nuget` packages.
I think we can then close #617
> Add MyGet reference to Readme.md

- NuGet/Readme.txt
Here's some additional words for the readme. Not a full pass obviously, but it's something. :)
Bill
> Some more edits for the NuGet readme.

- CefSharp.Core/Internals/ClientAdapter.cpp
- CefSharp/ILifeSpanHandler.cs
Here's the change we discussed in #884.
Bill
> Fix #884 by adding sourceUrl parameter to OnBeforePopup .Net callback.

- CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj
- CefSharp.BrowserSubprocess.Core/packages.config
- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/packages.config
- CefSharp.OffScreen.Example/CefSharp.OffScreen.Example.csproj
- CefSharp.OffScreen.Example/packages.config
- CefSharp.Test/CefSharp.Test.csproj
- CefSharp.Test/packages.config
- CefSharp.WinForms.Example/CefSharp.WinForms.Example.csproj
- CefSharp.WinForms.Example/packages.config
- CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj
- CefSharp.Wpf.Example/packages.config
Bug fix release on the `2171` branch.
> Upgrade to 3.2171.2069

- CefSharp.WinForms/Internals/ParentFormMessageInterceptor.cs
- CefSharp/CefSharp.csproj
- CefSharp/Internals/IntPtrExtensions.cs
Something like this maybe? 
Bill
> Fix #918 by adding extension method to cast from IntPtr to Int32

- CefSharp.Core/Cef.h
- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/CefSharp.Core.vcxproj.filters
- CefSharp.Core/Internals/PluginVisitor.h
- CefSharp.Example/CefExample.cs
- CefSharp/CefSharp.csproj
- CefSharp/Plugin.cs
Implement `CefVisitWebPluginInfo` using a simple `TaskCompletionSource` to notify when all plugins have been visited.
Also added `custom://cefsharp/plugins` that outputs a basic html table showing plugin details.
> Add CefVisitWebPluginInfo Wrapper

- CefSharp.Core/Cef.h
- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/CefSharp.Core.vcxproj.filters
- CefSharp.Core/Internals/CefTaskScheduler.h
- CefSharp.Core/ManagedCefBrowserAdapter.cpp
- CefSharp.Core/ManagedCefBrowserAdapter.h
- CefSharp.OffScreen/ChromiumWebBrowser.cs
- CefSharp.WinForms/ChromiumWebBrowser.cs
- CefSharp/CefSharp.csproj
- CefSharp/CefThreadIds.cs
As an added bonus, add GetZoomLevelAsync.
The bummer is that IOT_SetCookie/IOT_DeleteCookie wasn't worth converting over, even though I really would love doing that. CefCookie isn't allowed to be an `Action/Func` generic parameter due to it being a C++ template class.
> Add TaskFactories for UI/File/IO and use for GetZoomLevel

- CefSharp.Core/Internals/ClientAdapter.cpp
- CefSharp.Core/Internals/ClientAdapter.h
- CefSharp.Example/RequestHandler.cs
- CefSharp/IRequestHandler.cs
Implemented
- `OnResourceRedirect`
- `OnProtocolExecution`
- `OnQuotaRequest`
TODO: Cleanup method ordering to make alphabetical
> Implement Missing CefRequestHandler Methods

- CefSharp.Core/Cef.h
- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/CefSharp.Core.vcxproj.filters
- CefSharp.Core/CookieAsyncWrapper.h
- CefSharp.Core/SetCookieInvoker.h
Create wrapper class to call `SetCookie` async using new Task factory.
> Async SetCookie

- CefSharp.OffScreen/ChromiumWebBrowser.cs
- CefSharp.WinForms.Example/BrowserForm.cs
- CefSharp.WinForms/ChromiumWebBrowser.cs
- CefSharp.Wpf/ChromiumWebBrowser.cs
- CefSharp/IWebBrowser.cs
* Replace IWebBrowser.ZoomLevel property with:
GetZoomLevelAsync(), and SetZoomLevel().
> Continue the TaskScheduler items:

- CefSharp.Wpf/ChromiumWebBrowser.cs
> NullReferenceException in ChromiumWebBrowser if not yet in VisualTree

- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/CefSharp.Core.vcxproj.filters
- CefSharp.Core/Internals/ClientAdapter.cpp
- CefSharp.Core/Internals/RequestCallback.h
- CefSharp.Example/RequestHandler.cs
- CefSharp/CefSharp.csproj
- CefSharp/IRequestCallback.cs
- CefSharp/IRequestHandler.cs
Implement wrapper and expose for relevant `CefRequestHandler` interface methods
Resolves #982
Breaking `API` change for 
- `IRequestHandler.OnCertificateError`
- `IRequestHandler.OnQuotaRequest`
- `IRequestHandler.OnBeforeResourceLoad`
> Implement CefRequestCallback wrapper

- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/CefSharp.Core.vcxproj.filters
- CefSharp.Core/Internals/CefWindowInfoWrapper.h
- CefSharp.Core/Internals/ClientAdapter.cpp
- CefSharp/CefSharp.csproj
- CefSharp/ILifeSpanHandler.cs
- CefSharp/IWindowInfo.cs
Add Wrapper for CefWindoInfo (OnBeforePopup)
> Add CefWindowInfoWrapper

- CefSharp.OffScreen/CefSharp.OffScreen.csproj
- CefSharp/Properties/AssemblyInfo.cs
Cherry-picked commit adding missing strong name to CefSharp.Offscreen. If possible update nuget package after integrating.
> Sign the OffScreen project (using existing snk file)

- CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj
- CefSharp.BrowserSubprocess.Core/packages.config
- CefSharp.Core/Cef.h
- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/CookieAsyncWrapper.h
- CefSharp.Core/Internals/CefContextMenuParamsWrapper.cpp
- CefSharp.Core/Internals/CefContextMenuParamsWrapper.h
- CefSharp.Core/Internals/ClientAdapter.cpp
- CefSharp.Core/Internals/ClientAdapter.h
- CefSharp.Core/ResourceHandlerWrapper.cpp
- CefSharp.Core/packages.config
- CefSharp.Example/CefExample.cs
- CefSharp.OffScreen.Example/CefSharp.OffScreen.Example.csproj
- CefSharp.OffScreen.Example/packages.config
- CefSharp.Test/CefSharp.Test.csproj
- CefSharp.Test/packages.config
- CefSharp.WinForms.Example/CefSharp.WinForms.Example.csproj
- CefSharp.WinForms.Example/packages.config
- CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj
- CefSharp.Wpf.Example/packages.config
- CefSharp/DependencyChecker.cs
- CefSharp/IContextMenuParams.cs
- CefSharp3.sln
- build.ps1
- Update to latest `Nuget` packages
- Fixed breaking changes
> Upgraded to 3.2357.1274

- CefSharp.Core/BrowserSettings.h
- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/CefSharp.Core.vcxproj.filters
- CefSharp.Core/ManagedCefBrowserAdapter.cpp
- CefSharp.Core/ManagedCefBrowserAdapter.h
- CefSharp.Core/RequestContext.h
- CefSharp.Core/RequestContextSettings.h
- CefSharp.OffScreen.Example/Program.cs
- CefSharp.OffScreen/ChromiumWebBrowser.cs
- CefSharp.WinForms/ChromiumWebBrowser.cs
- CefSharp.Wpf/ChromiumWebBrowser.cs
Ability to set your own request context, browsers can share a custom set of settings
TODO create a wrapper around CefRequestContextSettings
> Add basic RequestContext Implementation

- CefSharp/Internals/PendingTaskRepository.cs
- CefSharp/Internals/TaskExtensions.cs
I found a bug in the pending task repository, tasks were always cancelled when a timeout is set.
> Pending tasks only cancelled on real timeouts

- CefSharp.Core/Internals/RenderClientAdapter.h
- CefSharp.Core/ManagedCefBrowserAdapter.cpp
- CefSharp.Wpf/ChromiumWebBrowser.cs
- CefSharp.Wpf/Rendering/BitmapFactory.cs
- CefSharp.Wpf/Rendering/WritableBitmapInfo.cs
- CefSharp/IBitmapFactory.cs
As far as I can see it works. I'll do some testing with this on our alpha release channel and see what happens.
> High Dpi again

- CefSharp.Core/Internals/ClientAdapter.cpp
Just a small fix for the latest changes on the master branch.
> Made sure that BitmapInfo is created for offscreen popup windows as well

- CefSharp.Core/Internals/CefTaskWrapper.h
Supposed to fix issue https://github.com/cefsharp/CefSharp/issues/1222.
> Fix issue with disposed tasks in .Net 4.0.

- CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj
- CefSharp.Core/CefSharp.Core.vcxproj
let cef.sdk reference from SolutionDir\packages not project relative parent
> Update cef.sdk.profs import to use SolutionDir

- CefSharp.Core/Cef.h
- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/CefSharp.Core.vcxproj.filters
- CefSharp.Core/Internals/CefGetGeolocationCallbackWrapper.h
- CefSharp/CefGeoPositionErrorCode.cs
- CefSharp/CefSharp.csproj
- CefSharp/Geoposition.cs
Implements #953
Not tested yet
> Add GetGeolocationAsync Implementation

- CefSharp.Core/Internals/ClientAdapter.cpp
- CefSharp.Core/Internals/ClientAdapter.h
- CefSharp.Example/RequestHandler.cs
- CefSharp/IRequestHandler.cs
Add new method to handler, relevant `CEF API` link:
http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRequestHandler.html#OnResourceResponse%28CefRefPtr%3CCefBrowser%3E,CefRefPtr%3CCefFrame%3E,CefRefPtr%3CCefRequest%3E,CefRefPtr%3CCefResponse%3E%29
> Add IRequestHandler.OnResourceResponse

- CefSharp.Example/Resources/FramedWebGLTest.html
- CefSharp.Example/Resources/PopupsTest.html
- CefSharp.Example/Resources/TooltipTest.html
replaced tabs for spaces in test html files
> Quickfix format test HTML files

- CefSharp.Example/CefSharp.Example.csproj
- CefSharp.Example/CefSharpSchemeHandler.cs
- CefSharp.Example/Properties/Resources.Designer.cs
- CefSharp.Example/Properties/Resources.resx
- CefSharp.Example/Resources/MultiBindingTest.html
- CefSharp.Example/Resources/PopupTest.html
added multi binding test for testing bindings with multiple contexts and dynamic context creation / destruction
- one browser, multiple changing contexts
- also added a link to the popuptest
#1315
> Feature multi binding test

- CefSharp.Core/Internals/ClientAdapter.cpp
- CefSharp.Core/Internals/ClientAdapter.h
- CefSharp.Core/Internals/TypeConversion.h
- CefSharp.Example/DragHandler.cs
- CefSharp/CefSharp.csproj
- CefSharp/DraggableRegion.cs
- CefSharp/IDragHandler.cs
> Implement IDragHandler.OnDraggableRegionsChanged

- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/CefSharp.Core.vcxproj.filters
- CefSharp.Core/Internals/CefRunContextMenuCallbackWrapper.h
- CefSharp.Core/Internals/ClientAdapter.cpp
- CefSharp.Core/Internals/ClientAdapter.h
- CefSharp.WinForms.Example/Handlers/MenuHandler.cs
- CefSharp.Wpf.Example/Handlers/MenuHandler.cs
- CefSharp/CefSharp.csproj
- CefSharp/IContextMenuHandler.cs
- CefSharp/IRunContextMenuCallback.cs
> Implement IContextMenuHandler.RunContextMenu

- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/CefSharp.Core.vcxproj.filters
- CefSharp.Core/RequestContext.h
- CefSharp.Core/RequestContextHandler.h
- CefSharp.Example/CefSharpSchemeHandlerFactory.cs
- CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj
- CefSharp.Wpf.Example/Handlers/PluginHandler.cs
- CefSharp.Wpf.Example/MainWindow.xaml
- CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs
- CefSharp/CefSharp.csproj
- CefSharp/IPluginHandler.cs
- CefSharp/PluginPolicy.cs
Can now be used through the RequestContext
Add Example to WPF application
> Implement IPluginHandler.OnBeforePluginLoad

- CefSharp/WebBrowserExtensions.cs
Add override to ExecuteScriptAsync extension that takes in a method name and array of params, then generates the relevant script and executes.
> ExecuteScriptAsync Execute method with params

- CefSharp.Core/Internals/CefFrameWrapper.cpp
- CefSharp.Core/Internals/CefFrameWrapper.h
- CefSharp.Core/Internals/CefPostDataElementWrapper.h
- CefSharp.Core/Internals/CefPostDataWrapper.h
- CefSharp.Core/Internals/CefRequestWrapper.cpp
- CefSharp.Core/Internals/CefRequestWrapper.h
- CefSharp.Wpf.Example/Controls/CefSharpCommands.cs
- CefSharp.Wpf.Example/MainWindow.xaml
- CefSharp.Wpf.Example/MainWindow.xaml.cs
- CefSharp.Wpf.Example/ViewModels/BrowserTabViewModel.cs
- CefSharp/IFrame.cs
- CefSharp/IPostData.cs
- CefSharp/IRequest.cs
- CefSharp/PostDataExtensions.cs
Expose IFrame.LoadRequest
Add IFrame.CreateRequest to instantiate a new instance of the CefRequestWrapper
Was planning on using VC++ extensions methods, have yet to get that working, so for now just have a method on the IFrame interface directly.
Resolves #912
> Implement IFrame.LoadRequest

- CefSharp.BrowserSubprocess.Core/Async/JavascriptAsyncMethodHandler.cpp
- CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp
- CefSharp.BrowserSubprocess.Core/Serialization/V8Serialization.cpp
- CefSharp.Core/Internals/ClientAdapter.cpp
- CefSharp.Core/Internals/JavascriptCallbackProxy.cpp
- CefSharp.Core/Internals/Messaging/Messages.h
- CefSharp.Core/Internals/Serialization/JsObjectsSerialization.cpp
- CefSharp.Core/Internals/Serialization/Primitives.cpp
- CefSharp.Core/Internals/Serialization/Primitives.h
- CefSharp.Core/Internals/Serialization/V8Serialization.cpp
- CefSharp.Example/RequestHandler.cs
- CefSharp/IRequestHandler.cs
Send an IPC message when OnContextCreated is called in the render process
Currently only called for the main frame
Should be possible to hook the DOMContentLoaded event
I've only tested using the sample code below, needs more testing before merging.
> Add IRenderProcessMessageHandler.OnContextCreated

- CefSharp.Wpf/ChromiumWebBrowser.cs
This will allow processing of modifier keys such as ctrl and shift during mouse wheel event.
> Send modifier keys during MousewWheel event

- CefSharp.Wpf.Example/Views/BrowserTabView.xaml
- CefSharp.Wpf/ChromiumWebBrowser.cs
Based on #1510 
- Uses a binding to set `BitmapScalingMode`
- Adds demo (dynamically set `BitmapScalingMode`)
>  Add BitmapScalingMode binding and demo

- CefSharp.Core/Internals/CefBrowserHostWrapper.cpp
- CefSharp.Wpf/ChromiumWebBrowser.cs
> Fixed Wpf ObjectDisposedException when quickly disposing ChromiumWebBrowser

- CefSharp/Internals/MethodRunnerQueue.cs
> MethodRunnerQueue target default scheduler

- CefSharp/Internals/MethodRunnerQueue.cs
This is to bring #1633 into the cefsharp/47 branch
> Target default scheduler  to fix #1630

- CefSharp/AddressChangedEventArgs.cs
- CefSharp/CEFCursorType.cs
- CefSharp/CefJsDialogType.cs
- CefSharp/CefReturnValue.cs
- CefSharp/CefState.cs
- CefSharp/DefaultResourceHandlerFactory.cs
- CefSharp/DragOperationsMask.cs
- CefSharp/DraggableRegion.cs
- CefSharp/IBrowserHost.cs
- CefSharp/ICookieVisitor.cs
- CefSharp/IDragData.cs
- CefSharp/IDragHandler.cs
- CefSharp/IPostDataElement.cs
- CefSharp/IStringVisitor.cs
- CefSharp/IWindowInfo.cs
- CefSharp/MouseEvent.cs
- CefSharp/PaintElementType.cs
- CefSharp/PostDataElementType.cs
- CefSharp/ReferrerPolicy.cs
- CefSharp/TransitionType.cs
- CefSharp/WebPluginInfo.cs
> Add some xml documentation

- NuGet/Readme.txt
Added link to Microsoft .NET Framework 4.5.2 for those needing it, for Visual Studio 2012 and 2013
> Update Nuget Readme.txt - Added link to .NET 4.5.2 Developer pack

- CefSharp.Core/Internals/TypeConversion.h
Adding support to convert `List` from `.Net` to `Native`
> Adding List type conversion

- CefSharp.Wpf.Example/Handlers/GeolocationHandler.cs
Here you go.
https://github.com/cefsharp/CefSharp/commit/4a9bc29971ff72ac9f7eef8f6aaca7ba47f2e849#commitcomment-18713664
> Fix hadle -> handle in comment

- CefSharp.WinForms/Internals/ControlExtensions.cs
this was fixed in https://github.com/cefsharp/CefSharp/pull/1132/commits/a99a04964421ab4c7587b5e07de821e973067a3e but hasnt been pulled into master.
> Fixing nullreferenceexception on ControlExtensions.IsActive

- README.md
Thank you for your hard work on this project.
> Fix grammar on readme

- CefSharp.BrowserSubprocess/CefSharp.BrowserSubprocess.csproj
> Re-sign x86 assembly in post build

- CefSharp/WindowOpenDisposition.cs
> Remove SuppressOpen enum value to line up with CEF

- CefSharp.Wpf/ChromiumWebBrowser.cs
Resolves #1861
- Prevent `image` and `popup` from getting created more than once
> Fixed WPF browser going blank when connecting over RDP

- CefSharp.Core/Internals/ClientAdapter.cpp
Resolves #1960
- Fixed the NullReferenceException specified in the issue
> Fixed NullReferenceException in DoClose

- CefSharp.Core/Internals/ClientAdapter.cpp
- CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj
- CefSharp.Wpf.Example/Handlers/DisplayHandler.cs
- CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs
- CefSharp/Handler/IDisplayHandler.cs
Resolves #1648
- Made it possible to modify the `text` parameter
- Updated the examples accordingly
- Added a DisplayHandler to the WPF example
> Updated OnTooltipChanged to allow for modifying text

- CefSharp.BrowserSubprocess.Core/CefSharp.BrowserSubprocess.Core.vcxproj
- CefSharp.BrowserSubprocess.Core/packages.config
- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/PopupFeatures.h
- CefSharp.Core/packages.config
- CefSharp.OffScreen.Example/CefSharp.OffScreen.Example.csproj
- CefSharp.OffScreen.Example/crash_reporter.cfg
- CefSharp.OffScreen.Example/packages.config
- CefSharp.Test/CefSharp.Test.csproj
- CefSharp.Test/packages.config
- CefSharp.WinForms.Example/CefSharp.WinForms.Example.csproj
- CefSharp.WinForms.Example/crash_reporter.cfg
- CefSharp.WinForms.Example/packages.config
- CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj
- CefSharp.Wpf.Example/crash_reporter.cfg
- CefSharp.Wpf.Example/packages.config
- CefSharp/IPopupFeatures.cs
- README.md
- appveyor.yml
Feel free to chime in - fixes part of #2200. 🎉
The issue with JS bindings being lost have not been sorted out in this PR, I intend to look at that in a separate PR before we do the release. This compiles and runs for me, and looks pretty neat:
> Upgraded to CEF 62

- README.md
Hi All,
This is is the link to a project I have been working on for sometime now, and would like to share with the community. The project uses CefSharp, CefGlue.
I hope it meets the required standards.
Thank you.
> Request to add a github link to the "Link" list.

- CefSharp.WinForms/CefSharp.WinForms.csproj
This PR reverts a build breaking change in `master`
> Revert build breaking change

- CefSharp.Wpf/ChromiumWebBrowser.cs
https://github.com/cefsharp/CefSharp/commit/a086b4b7802da4d8ddc60a38e309968ba8d4cce6
> add missing space in exception message

- CefSharp.WinForms/ChromiumWebBrowser.cs
Continuation of https://github.com/cefsharp/CefSharp/pull/2261
This PR sets the default values for the rest of the properties that aren't visible to the designer
> WinForms: Prevent designer from setting any default values

- CefSharp.Wpf/ChromiumWebBrowser.cs
if the visual is not connected the whole application will crash
> check if the visual is connected

- CefSharp.Core/Internals/Serialization/V8Serialization.cpp
- CefSharp.Example/AsyncBoundObject.cs
- CefSharp.Example/Resources/BindingTest.html
Handle Dictionary type, otherwise it will be treated as class/structs and cause exception.
> Serialize Dictionary type to V8 object

- CefSharp.Test/OffScreen/OffScreenBrowserBasicFacts.cs
- CefSharp/WebBrowserExtensions.cs
Added string encoding and test to ensure strings pass to js and comes back unchanged.
Test can easily be modified with other string features
> #2339 Encode string parameters for EvaluateScriptAsync (IWebBrowser, String,Object[]) 

- CefSharp.Core/Cef.h
Fixed a typo in summary of ShutdownWithoutChecks().
> Fixed a typo

- CefSharp/DependencyChecker.cs
Updated DependencyChecker to include v8_context_snapshot.bin
Fixes #2399
> Update DependencyChecker with now required "v8_context_snapshot.bin"

- CefSharp.Wpf/ChromiumWebBrowser.cs
Fix possible null reference of RenderHandler in second part of condition.
> Fix possible null reference of RenderHandler

- CefSharp.BrowserSubprocess/Program.cs
I was seeing instances of the subprocess being spawned this way when running the CefSharp.Wpf.Example project.
```
Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
at System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
at System.Number.ParseInt32(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
at System.Int32.Parse(System.String)
at CefSharp.BrowserSubprocess.Program.Main(System.String[])
```
Debugging showed me that no such argument was being passed to the process in these cases:
This PR works around the issue by …
> Bug fix: handle type=crashpad-handler

- CefSharp.Wpf/CefSharp.Wpf.csproj
- CefSharp.Wpf/ChromiumWebBrowser.cs
- CefSharp.Wpf/Themes/Generic.xaml
Based on #1499
Additionally Popup is created in xaml
Canvas used to absolute position the two images, one on top of the other
No Mouse.Capture required
Much simpler implementation, not very well tested yet.
> WPF - ChromiumWebBrowser inherit from Control rather than UserControl

- CefSharp.BrowserSubprocess.Core/RegisterBoundObjectHandler.h
- CefSharp.Wpf/ChromiumWebBrowser.cs
Fixed small typo and removed excessive null-check.
> Small typo and excessive null-check

- CefSharp.OffScreen.Example/CefSharp.OffScreen.Example.csproj
- CefSharp.OffScreen.Example/packages.config
- CefSharp.WinForms.Example/CefSharp.WinForms.Example.csproj
- CefSharp.WinForms.Example/packages.config
- CefSharp.Wpf.Example/CefSharp.Wpf.Example.csproj
- CefSharp.Wpf.Example/packages.config
~Added the nuget package `System.Security.Principal.Windows` to fix a `System.IO.FileNotFoundException` during build.~
Upgraded `Microsoft.Net.Compilers` to V2.9 to fix a `System.IO.FileNotFoundException` during build
Resolves #2508
> Fixed System.IO.FileNotFoundException during build

- CefSharp/SchemeHandler/FolderSchemeHandlerFactory.cs
This small change will allow hot edit and reload for local pages, which is helpful for development purposes.
> FolderSchemeHandlerFactory - change resource file share mode.

- README.md
Updated link to salt to actual salt project page and added a note up top.
> Updated readme donation information

- CefSharp.Core/Internals/ClientAdapter.cpp
> Make sure frame is not null before accessing it

- CefSharp.Core/Cef.h
introduced in https://github.com/cefsharp/CefSharp/commit/65408138493030f64563f4acbfa38a0fe0f5a1cf
> fix OffScreen spelling in Cef.h

- CefSharp.Core/Cef.h
- CefSharp.Core/CefSharp.Core.vcxproj
- CefSharp.Core/CefSharp.Core.vcxproj.filters
- CefSharp.Core/Internals/CefSchemeRegistrarWrapper.h
- CefSharp.Core/Internals/CefSharpApp.h
- CefSharp/CefCustomScheme.cs
- CefSharp/CefSharp.csproj
- CefSharp/DefaultApp.cs
- CefSharp/IApp.cs
- CefSharp/ISchemeRegistrar.cs
Move code from Cef.Initialize into CefSharpApp
Working towards #2139
> Add IApp interface and DefaultApp implementation

- CefSharp.Core/Cef.h
- CefSharp.Example/Handlers/BrowserProcessHandler.cs
- CefSharp.OffScreen.Example/Program.cs
- CefSharp.OffScreen/ChromiumWebBrowser.cs
- CefSharp.WinForms.Example/Program.cs
- CefSharp.WinForms/ChromiumWebBrowser.cs
- CefSharp.Wpf/ChromiumWebBrowser.cs
- CefSharp/WebBrowserExtensions.cs
some exception messages which span over multiple lines are missing spaces between words
> add spaces in exception messages

- .github/no-response.yml
- .github/support.yml
- Added config for `no-response` and `support` bot
> Added config for no-response and support bot

- .editorconfig
- CefSharp.WinForms/ChromiumWebBrowser.cs
- Added `csharp_indent_case_contents_when_block = false` to `EditorConfig`
> EditorConfig: Added missing csharp_indent_case_contents_when_block

- CefSharp.Core/ManagedCefBrowserAdapter.cpp
also updated spelling to be consistent with new changes.
> Add space in exception message

- CefSharp.Wpf.Example/ViewModels/BrowserTabViewModel.cs
Simple null check to prevent App crash if we close a tab during a test.
Closes: https://github.com/cefsharp/CefSharp/issues/2722
> [WPF.Example] Null check

- CefSharp.Wpf/ChromiumWebBrowser.cs
> Add TemplatePart Attributes to ChromiumBrowser

- CefSharp.Wpf/Experimental/WpfIMEKeyboardHandler.cs
Fixes some issues with https://github.com/cefsharp/CefSharp/issues/1262
> WPF Experimental  - Fixed IME window not showing or showing at the wrong location

- README.md
> README.md - Use https

- CefSharp.OffScreen/ChromiumWebBrowser.cs
Changed typeof requestContext to IRequestContext in ChromiumWebBrowser.ctor
My requestContext was returned from RequestContext.CreateContext()
> OffScreen - ChromiumWebBrowser constructor change RequestContext to IRequestContext

- README.md
Fixes [issue-number] 
Update the documents.
Due to the CefGlue has move to a new url.
Update the documents.
**Checklist:**
> update CefGlue source code link;

- CefSharp.Wpf/ChromiumWebBrowser.cs
Fixes crash issue in #2779 
**Summary:**
Fixed the crashes that could occur when running on the CEF UI thread async in the updated 2779 hack.
**Changes:**
CefUiThreadRunAsync is now awaited on and I also moved some more code to run on the CEF UI thread. All necessary to avoid the crashing. I made sure to test after each change so nothing is running on that thread that doesn't need to.
I ran the crash test code found in the WPF example MainWindow.xaml.cs on this branch: https://github.com/mol/CefSharp/tree/reworkedhack2779 again and again and again after each modification to see if the crashes would stop or not. I also went back and forth with my changes to ensure only the necessary changes were made to stop the crashing.
**Checklist:**
> WPF - Updated #2779 hack to run asynchronous without crashing.

- CefSharp.Core/RequestContext.cpp
- CefSharp.Core/RequestContext.h
- CefSharp/IRequestContext.cs
Fixes #2957
**Summary:**
- I have added a new feature to the RequestContext implementation
**Changes:**
- I have modified the RequestContext Implementation
- Added support for ClearHttpAuthCredentials
No testing yet.
**Checklist:**
> Add RequestContext.ClearHttpAuthCredentials

- CefSharp.WinForms/ChromiumWebBrowser.cs
- CefSharp.Wpf/ChromiumWebBrowser.cs
- CefSharp/ICookieManager.cs
**Summary:**
- Typos
**Checklist:**
> Fix a typo in an error message

- CefSharp.WinForms/ChromiumWebBrowser.cs
Resolves #2042
**Summary:** 
Use a parkingControl as a temporary parent for the CefBrowser while the handle is recreating.
https://docs.microsoft.com/en-us/archive/blogs/sburke/flashback-windows-forms-parking-window
Issue #2840 should now create a new browser correctly when the MdiParent is changed,
the browser state won't be persisted, I believe this is expected as detailed in the .Net Source
https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Form.cs,1925
When toggling ShowInTaskbar when the browser is hosted in a TabControl then the handle isn't
actually recreated yet the browser is effectively parked, perhaps the .Net source has some tricks
we can use to further improve the case when using  MdiParent
**Changes:**
Set browser parent to a temp …
> WinForms - RecreatingHandle re-parent browser to parkingControl

- NuGet/CefSharp.Common.targets
- NuGet/CefSharp.OffScreen.targets
- NuGet/CefSharp.WinForms.targets
- NuGet/CefSharp.Wpf.targets
**Summary:**
Fixes whitespace in `.targets` files to use spaces.
**Checklist:**
> Fix whitespace in .targets files

- CefSharp/WebBrowserExtensions.cs
Spelling mistakes 
Update xml doc
**Checklist:**
> WebBrowserExtensions fix Spelling mistakes 

- CefSharp.Test/OffScreen/OffScreenBrowserBasicFacts.cs
**Summary:** Added test for 4b2fe1e0d7c43e94c851bada433efb0e1c7b7952
Best viewed without whitespace changes.
**Changes:**
- Added test for 4b2fe1e0d7c43e94c851bada433efb0e1c7b7952
- Dispose browser in `CrossSiteNavigationJavascriptBinding` test
- Unittest
**Checklist:**
> add test for binding object multiple times

- CefSharp.BrowserSubprocess.Core/Async/JavascriptAsyncMethodHandler.cpp
- CefSharp.BrowserSubprocess.Core/BindObjectAsyncHandler.h
- CefSharp.BrowserSubprocess.Core/Serialization/JsObjectsSerialization.cpp
- CefSharp.BrowserSubprocess.Core/Serialization/V8Serialization.cpp
- CefSharp.Core/Internals/CefExtensionWrapper.cpp
- CefSharp.Core/Internals/CefValueWrapper.cpp
- CefSharp.Core/Internals/ClientAdapter.cpp
- CefSharp.Core/Internals/Serialization/ObjectsSerialization.cpp
- CefSharp.Core/Internals/Serialization/Primitives.h
- CefSharp.Core/Internals/Serialization/V8Serialization.h
- CefSharp.Core/Internals/TypeConversion.h
**Fixes:** N/A
When code analysis is enabled, multiple issues like the following one are found:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4018	'<': signed/unsigned mismatch	CefSharp.BrowserSubprocess.Core	c:\repos\cefsharp\cefsharp.browsersubprocess.core\serialization\jsobjectsserialization.cpp	71
```
**Changes:**
Replace multiple `auto` with `size_t` to make sure compiler does not pick `int` by default.
I ran the examples manually.
**Checklist:**
> Fix code analysis C4018 warnings

- README.md
**Fixes:** N/A
**Summary:** I have added Chromely CefSharp to "Projects using CefSharp" section.
**Changes:** Modified ReadMe.
**How Has This Been Tested?**  N/A
**Screenshots (if appropriate):** N/A
**Checklist:**
> Adding Chromely to "Projects using CefSharp"

- CefSharp.Test/DevTools/DevToolsClientFacts.cs
- CefSharp/DevTools/DevToolsDomainEntityBase.cs
**Fixes:**
https://github.com/cefsharp/CefSharp/discussions/3485#discussioncomment-585699
**Summary:**
- Add special case for serializing `IList<DevToolsDomainEntityBase>` dev tools parameters.
unittest
**Checklist:**
> DevTools - Serialize lists of DevToolsDomainEntityBase

- CefSharp.Core/CefSharp.Core.csproj
- CefSharp.Core/Fluent/DownloadHandler.cs
- CefSharp.Core/Fluent/DownloadHandlerBuilder.cs
- CefSharp.Core/Fluent/UrlRequestClient.cs
- CefSharp.Core/Fluent/UrlRequestClientBuilder.cs
- CefSharp.Core/WebBrowserExtensionsEx.cs
- CefSharp.Test/OffScreen/OffScreenBrowserBasicFacts.cs
- CefSharp/CefSharp.csproj
- CefSharp/IBrowserHost.cs
- CefSharp/Internals/TaskExtensions.cs
- CefSharp/UrlRequestClient.cs
- CefSharp/WebBrowserExtensions.cs
**Fixes:**
Issue #3550
**Summary:** 
- Add new IFrame.DownloadUrlAsync and IFrame.DownloadUrl methods
- Add Fluent DownloadHandler Implementation
**Changes:** 
- Enhancements
- Unit Tests Included
**Checklist:**
> Add Fluent DownloadHandler

- CefSharp.Test/DevTools/DevToolsClientFacts.cs
- CefSharp.Test/JavascriptBinding/IntegrationTestFacts.cs
- CefSharp.Test/OffScreen/OffScreenBrowserBasicFacts.cs
- CefSharp.Test/PostMessage/IntegrationTestFacts.cs
- CefSharp.Test/WebBrowserTestExtensions.cs
- CefSharp.Test/WinForms/WinFormsBrowserBasicFacts.cs
- CefSharp.Test/Wpf/WpfBrowserBasicFacts.cs
- CefSharp/CefSharp.csproj
- CefSharp/IWebBrowser.cs
- CefSharp/Internals/Partial/ChromiumWebBrowser.Partial.cs
- CefSharp/LoadUrlAsyncResponse.cs
- CefSharp/WebBrowserExtensions.cs
**Summary:** 
- Adds a method that can await the loading of a page (using `LoadingStateChanged`)
**Changes:** 
- New method added
- Test cases updated to use the new method
- Unit tests have been updated to use the new method
**Checklist:**
> Enhancement - Add LoadUrlAsync

- CefSharp.Core.Runtime/Internals/CefBrowserHostWrapper.cpp
**Fixes:** https://github.com/cefsharp/CefSharp/pull/3627#issuecomment-872552452
**Summary:**
- Backports https://bitbucket.org/chromiumembedded/cef/pull-requests/377 as it now merged.
**Changes:**
- Simplifies Shift + AltGr logic
Manually using `CefSharp.Wpf.Example`
Second letter is AltGr + Shift + ß => ẞ
**Checklist:**
> WPF - Simplify Support Shift + AltGr

- CefSharp/Enums/CefErrorCode.cs
**Related:** https://github.com/cefsharp/CefSharp/discussions/3784
**Summary:**
- Updated CefErrorCodes using https://raw.githubusercontent.com/chromium/chromium/92.0.4515.176/net/base/net_error_list.h as source
**Changes:**
- Goto https://raw.githubusercontent.com/chromium/chromium/92.0.4515.176/net/base/net_error_list.h
- Open DevTools
- Run the following javascript in the console which will copy the result into the clipboard and paste it in the `CefErrorCodes` file.
```js
var text = document.documentElement.textContent,
result = [],
comment = [];
text.split("\n").forEach(line => {
if (!line) {
if (comment.length > 0) {
result.push("", ...comment);
comment = [];
}
}
else if (line.startsWith("//")) {
comment.push(line);
}
else if (line.startsWith("NET_ERROR")) {
result.push(
"",
"/// …
```
> Core - Update CefErrorCodes

- README.md
**Summary:**
- Make API reference link version independent
**Checklist:**
> Readme - Make API reference link version independent

- CefSharp/Enums/CefErrorCode.cs
**Related:** https://github.com/cefsharp/CefSharp/issues/3956
**Summary:** Updated CefErrorCode using https://raw.githubusercontent.com/chromium/chromium/97.0.4692.71/net/base/net_error_list.h and steps described in #3785
Build works.
**Checklist:**
> Core - Update CefErrorCode

- CefSharp.Test/Selector/WaitForSelectorAsyncTests.cs
- CefSharp/JavascriptResponse.cs
- CefSharp/WaitForSelectorAsyncResponse.cs
- CefSharp/WebBrowserExtensions.cs
**Fixes:**
Issue #4094
**Summary:** 
Adds new WaitForSelectorAsync extension method
- Add WaitForSelectorAsync extension method
- Add tests
xUnit Tests added
**Checklist:**
> Enhancement - Add WaitForSelectorAsync extension method.

- CefSharp.Wpf/ChromiumWebBrowser.cs
**Fixes:**
- Fixes issue 4274
**Summary:**
- Re-Added the resize hack for issue 2779, as the issue still occurs. Disabled by default as mentioned by @amaitland in https://github.com/cefsharp/CefSharp/discussions/4274#discussioncomment-3946056
**Changes:**
- Re-Added the resize hack for issue 2779
- Ported changes to match master (Execution of the resize hack has been moved to OnBrowserWasHidden)
- This was tested with the CefSharp minimal example, creating multiple browsers (at least 6 are needed) and toggling the visibility of the browsers.
- OS: Win10, x64
> WPF - Add simplified resize hack (disabled by default)

- build.ps1
**Summary:**
Allow using Visual Studio Build Tools as a build environment
**Changes:**
Build Tools are used as a fallback, when discovering the VS path with vswhere. If a VS IDE is installed, the behavior is unchanged.
vswhere does not discover Build Tools if the "-products" option is not specified.
Docker image with Visual Studio Build Tools 2022 installed
```
> ./build.ps1 -BuildArches "x86 x64" -Verbose -Target "vs2022" -Version 106.0.290 -AssemblyVersion 106.0.290 -TargetFramework "NetFramework"
CEF Redist Version = 106.0.29
Restore Nuget Packages
Alle in "packages.config" aufgefÃ¼hrten Pakete sind bereits installiert.
Alle in "packages.config" aufgefÃ¼hrten Pakete sind bereits installiert.
VSWhere path C:\Program Files (x86)\Microsoft Visual …
```
> Add Visual Studio Build Tools support

- NuGet/CefSharp.Common.nuspec
- NuGet/CefSharp.OffScreen.nuspec
- NuGet/CefSharp.WinForms.nuspec
- NuGet/CefSharp.Wpf.nuspec
- NuGet/PackageReference/CefSharp.Common.NETCore.nuspec
- NuGet/PackageReference/CefSharp.OffScreen.NETCore.nuspec
- NuGet/PackageReference/CefSharp.WinForms.NETCore.nuspec
- NuGet/PackageReference/CefSharp.Wpf.NETCore.nuspec
- build.ps1
**Fixes:** https://github.com/cefsharp/CefSharp/issues/4762
**Summary:**
- Added [<repository>](https://learn.microsoft.com/en-us/nuget/reference/nuspec#repository) to nuspec with support for branch and commit
Manually
**Checklist:**
> Nuget - Add repository to nuspec

- CefSharp.Core/DevTools/DevToolsClient.cs
**Summary:**
- JsonSerializerOptions should be reused when possible: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/configure-options?pivots=dotnet-8-0#reuse-jsonserializeroptions-instances
**Changes:**
- Reuse JsonSerializerOptions and DataContractJsonSerializerSettings
**How Has This Been Tested?**
Unittests
**Checklist:**
> Core - DevToolsClient reuse json serializer options / settings

- CefSharp.Test/Javascript/JavascriptCallbackTests.cs
**Summary:**
- Use Invariant Culture for double ToString to make tests pass in other locales (like german)
**Changes:**
- Use Invariant Culture for double ToString to make tests pass in other locales (like german)
Same as the other ones:
https://github.com/cefsharp/CefSharp/blob/1eb7f1036872b835e57bcf1be2bef630d7244911/CefSharp.Test/Javascript/EvaluateScriptAsyncGenericTests.cs?plain=1#L54-L61
https://github.com/cefsharp/CefSharp/blob/1eb7f1036872b835e57bcf1be2bef630d7244911/CefSharp.Test/Javascript/EvaluateScriptAsyncTests.cs?plain=1#L63-L76
- Running Tests
**Checklist:**
> Test - Use invariant culture for double ToString

- CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp
- CefSharp.Wpf.HwndHost.Example/MainWindow.xaml
Related issue in CEF:  [3867](https://github.com/chromiumembedded/cef/issues/3867)
**Summary:**
- Removed multiple calls to IRenderProcessMessageHandler.OnContextCreated
**Checklist:**
> Fixed duplicate calls to OnContextCreated
